### ISSUE TITLE
Status not updating or incorrect in iOS Home app

### ISSUE THREAD

**Issue by moored** [iRayanKhan/homebridge-chamberlain#1]
Opening and Closing the doors is working correctly however the status does not update consistently. If I force quit the app on one device and launch it again the status will update correctly on the others. I am not sure if this is an issue with the plugin, the homebridge server or iOS. The console output from the homebridge server is showing the correct status.

Posting here to see if others are experiencing the same behavior. 

iOS 10.0.1, iPad Pro 9.7" & iPhone 7

**Comment by caseywebdev** [comment]
You found this quick! I've made a bunch of improvements to the status updating in the last couple days, please try again with version `0.0.11`.

**Comment by caseywebdev** [comment]
Got stuck on `Opening...` for me today in the Home app after opening and closing the door, but the logs read everything was working exactly as expected. At this point I'm inclined to believe this is an issue with Homebridge or the Home app. I'm going to dig into the Homebridge code and see if anything looks suspicious.

**Comment by caseywebdev** [comment]
I think we can rule out Homebridge because if you ask Siri, she reports the correct state, which means Homebridge is correctly reporting the current state to HomeKit, the Home app is just not displaying it correctly.

**Comment by caseywebdev** [comment]
In the homebridge slack channel:

```
khaost [10:20 PM]  
@schindog44 Home app uses current characteristic to determine the final state

[10:20]  
@schindog44 if the accessory reports a different current/target state, Home app will show the transitional state
```

With that knowledge, I was able to update the code to prevent the target state from getting left behind when the garage door is opened/closed via something other than HomeKit. This should no longer be an issue.

**Comment by jagpreetbatth** [comment]
how did you update the code? 
Im using homebridge-chamberlain as an accesory  in config.json and still not able to get status from "Opening..." to actual "OPEN"???
Any ideas?
