### ISSUE TITLE
Thank you for api.js

### ISSUE THREAD

**Issue by adamcoulombe** [iRayanKhan/homebridge-chamberlain#101]
Hey, this is not really a bug or feature request, but I wanted to say thank you for the v5 API library (api.js), which I was able to use in a separate project. As you know there is not much public API documentation, but I found this repo to be the most up to date.

It would make a great standalone npm library.

Thanks again!

**Comment by iRayanKhan** [comment]
Thank you for the feedback! I'm glad it worked for you. There are separate node projects with way more documentation regarding the V5 api. I'm not sure if that are updated for V5.1. What other project are you using this for, just curious.

**Comment by adamcoulombe** [comment]
I believe grabbing the security token required more/different parameters in 5.1 vs. 5.0.

I am basically using it to run a little express setup, and using Apple Shortcuts to hook into it and create some different shortcuts & Siri commands. I also have some Integration with google assistant via ifttt.

I had previously written my own lib for v3 a while back, but it hasn’t been working for at least a few months now, so I finally got around to fixing it.
