### ISSUE TITLE
Error: invalid response, got HTTP 400:

### ISSUE THREAD

**Issue by nflute** [iRayanKhan/homebridge-chamberlain#105]
# Explain the issue occuring:
My garage door is "No Response" and I received this HTTP 400 Error message today.  MyQ app is working without problem. 

I do not make any change. Restarting homebridge does not help. 

Anyone come across this issue before, any idea on how to fix this?

# Info
Plugin Version: homebridge-chamberlain v1.6.0
HomeBridge Version: Version 1.1.1
Node/Npm Version: v12.18.1/v6.14.5

# Log Output:

[6/25/2020, 11:47:29 AM] [Garage Door] Error: invalid response, got HTTP 400: {
    "SecurityToken": "",
    "ReturnCode": "0",
    "ErrorMessage": "please contact customer care, supportID: "11621071379429749844",
    "CorrelationId": ""
}
    at /usr/lib/node_modules/homebridge-chamberlain/src/api.js:27:15
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by FearTheGrackle** [comment]
I'm having the same issues today...  Lost internet for an hour or so, and after it came back I had the same...  I've been racking my brain trying to figure out if related, but since you see the same issue I assume its not...  phew...  locked myself out of the house though until I found our extra key hidden outside lol

[6/25/2020, 2:00:51 PM] [Garage Door] Error: invalid response, got HTTP 400: {
    "SecurityToken": "",
    "ReturnCode": "0",
    "ErrorMessage": "please contact customer care, supportID: " 1006672810473381074",
    "CorrelationId": ""
}
    at /homebridge/node_modules/homebridge-chamberlain/src/api.js:27:15
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by schmidt660** [comment]
> # Explain the issue occuring:
> My garage door is "No Response" and I received this HTTP 400 Error message today. MyQ app is working without problem.
> 
> I do not make any change. Restarting homebridge does not help.
> 
> Anyone come across this issue before, any idea on how to fix this?
> 
> # Info
> Plugin Version: homebridge-chamberlain v1.6.0
> HomeBridge Version: Version 1.1.1
> Node/Npm Version: v12.18.1/v6.14.5
> 
> # Log Output:
> [6/25/2020, 11:47:29 AM] [Garage Door] Error: invalid response, got HTTP 400: {
> "SecurityToken": "",
> "ReturnCode": "0",
> "ErrorMessage": "please contact customer care, supportID: "11621071379429749844",
> "CorrelationId": ""
> }
> at /usr/lib/node_modules/homebridge-chamberlain/src/api.js:27:15
> at runMicrotasks ()
> at processTicksAndRejections (internal/process/task_queues.js:97:5)

Same issue here. Happened at some point today. Guessing another API change?

**Comment by ghost** [comment]
Same issue here.

**Comment by FearTheGrackle** [comment]
Forgot to mention:

Timezone | GMT-0500
-- | --
Alpine Linux (3.12.0)
v12.18.1
v6.14.5
root
/homebridge
/homebridge/config.json
/homebridge/node_modules
Yes

**Comment by iRayanKhan** [comment]
I hope the API didn't change again. My stuff isn't responding anymore either. I'll look into it, but if anyone is able to extract any new api info, please submit a PR.

**Comment by bdjett** [comment]
Took a quick look at this, looks like MyQ has just blocked the app build number in the User-Agent. Updating it to `myQ/19569` (the current build in the App Store) seems to work.

**Comment by Moneyroks2** [comment]
Same issue. 

Your on top of it IRayanKhan! Thanks being so responsive to your plugin's users!

**Comment by magnus319** [comment]
> Took a quick look at this, looks like MyQ has just blocked the app build number in the User-Agent. Updating it to `myQ/19569` (the current build in the App Store) seems to work.

That works, thanks.

**Comment by a-rodriguez** [comment]
Glad I am not the only one.

**Comment by mbierman** [comment]
Same here.

**Comment by HunterJKirby** [comment]
> Took a quick look at this, looks like MyQ has just blocked the app build number in the User-Agent. Updating it to `myQ/19569` (the current build in the App Store) seems to work.

How would someone go about changing the user agent? I’m relatively new.

**Comment by FearTheGrackle** [comment]
can confirm changing line in src/api.js to "      'User-Agent': 'myQ/19569 CFNetwork/1107.1 Darwin/19.0.0'," worked!

**Comment by FearTheGrackle** [comment]
> > Took a quick look at this, looks like MyQ has just blocked the app build number in the User-Agent. Updating it to `myQ/19569` (the current build in the App Store) seems to work.
> 
> How would someone go about changing the user agent? I’m relatively new.

In your home bridge docker config directory find the api.js (for me its /home/<myusername>/config/homebridge/node_modules/homebridge-chamberlain#)

Line 17 ( I think) you'll see User-Agent setting, just edit out the myQ/<whatever number was there> to myQ/19569 and save, restart home bridge...

That being said I'm sure @iRayanKhan is going to push a new build of the plugin very shortly, might as well just wait

**Comment by mbierman** [comment]
@FearTheGrackle @iRayanKhan would it make sense to make this a config item so that if it changes again it doesn't require a release for people to just tweak it on their own? I know, that might be overkill, just a thought.

**Comment by HunterJKirby** [comment]
Changed it and works perfectly. Thank you!

**Comment by mbierman** [comment]
The fix seems to have worked for me too.

**Comment by mwhaley99** [comment]
Same issue here using HOOBS

**Comment by iRayanKhan** [comment]
> @FearTheGrackle @iRayanKhan would it make sense to make this a config item so that if it changes again it doesn't require a release for people to just tweak it on their own? I know, that might be overkill, just a thought.
>> Yes, I will add this soon. I am working on other projects, and right after releasing V2 of homebridge-tuya, I will make this a config option.

And thank you @bdjett and @FearTheGrackle for finding out this info. I will publish a new build, and it will be live on NPM within the next 15-30 minutes.

**Comment by mwhaley99** [comment]
Thanks !

How will I update Hoobs with your new update ?

Regards
Mark Whaley

**Comment by iRayanKhan** [comment]
>> I don't know what the HOOBS interface is like, but I imagine it would day "x Plugin(s) are out of date". So just update it like that.
@mwhaley99

**Comment by iRayanKhan** [comment]
Closed:

Please update the plugin to the latest release.

**Comment by andrewturko** [comment]
@iRayanKhan Thank you for the fast response on this. I'm not seeing the new build on npm, do you have an ETA on when this'll be live (needed for update via config-ui-x)?

**Comment by iRayanKhan** [comment]
NPM shows its published on my end

**Comment by kevinjgibb** [comment]
@mwhaley99, just go to Hoobs/local then plugins and select Update under Chamberlain.  Thank you @iRayanKhan for the fix!

**Comment by mwhaley99** [comment]
Thanks, updated and working again. 

Regards
Mark Whaley

**Comment by furenberger** [comment]
@bdjett Where in the app store do you see that 19569?  I'm wondering if it is something I can scrape off of their site?

**Comment by chris-jh** [comment]
I have updated to latest and the api has 19569 and i am getting this error.

Where do you find the new version numbers?
