### ISSUE TITLE
Starting 7/1/2020 the garage door gives "No Response"

### ISSUE THREAD

**Issue by nvdokh** [iRayanKhan/homebridge-chamberlain#108]
It looks like there has been a change in myQ API preventing the homebridge module from working.

**Comment by helioyanagita** [comment]
I am getting the following error, wondering if this may be related to the myQ API change referenced above.. 

[7/1/2020, 6:49:18 PM] [Main Garage Door] Error: invalid response, got HTTP 400: {
    "SecurityToken": "",
    "ReturnCode": "0",
    "ErrorMessage": "please contact customer care, supportID: "  0899182882",
    "CorrelationId": ""
}
    at /usr/local/lib/node_modules/homebridge-chamberlain/src/api.js:27:15
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by DMBlakeley** [comment]
@bdjett, when this happened before you posted:

_Took a quick look at this, looks like MyQ has just blocked the app build number in the User-Agent. Updating it to myQ/19569 (the current build in the App Store) seems to work._

How did you find out the current app build number as I cannot seem to find in the App Store?

**Comment by DMBlakeley** [comment]
Found the build number at bottom of the Account page for the MyQ iOS app (19859). Unfortunately not that simple of a change.

**Comment by iRayanKhan** [comment]
Are y’all on the latest plugin update? Published a new version a day or so ago.

**Comment by nvdokh** [comment]
I am.

**Comment by iRayanKhan** [comment]
Try re-updating the plugin, this issue should have been resolved since I updated the User-Agent.

**Comment by nvdokh** [comment]
Uninstalling/reinstalling the plugin didn't fix the issue.

**Comment by zirdum** [comment]
The MyQ2 plugin is having his same issue. Apparently it's because Chamberlain/Liftmaster updated their API to v5 which broke some things for these plugins.

**Comment by iRayanKhan** [comment]
My garages work fine, and this doesn't seem to be widespread. What kind of garages are y'all using?

**Comment by leehendricks** [comment]
1.6.1 fixed the problem for me. Liftmaster 8155 with 828LM LiftMaster Internet Gateway

**Comment by furenberger** [comment]
in other packages they are removing the agent altogether or moving to okhttp.  the MR for 2.0 works with in all cases with the agent removed altogether, the agent of `okhttp/3.10.0` (as found in the latest android build) and the agent of `myQ/19569 CFNetwork/1107.1 Darwin/19.0.0`.  

I have a LIftmaster with the LiftMaster 828LM

see related https://github.com/arraylabs/pymyq/pull/47/files

**Comment by thatsjet** [comment]
I have the same error message @helioyanagita mentioned above. Mine is a MyQ add on hub with older Chamberlain drive. Running MyQ iOS 5.158.19859.

**Comment by iRayanKhan** [comment]
I wonder if they didn't push out an update for that hub and doesn't use V5.1. Not sure how to proceed further atm.

**Comment by furenberger** [comment]
In v2 we can put the header var in a config setting so you can change this in config ui.

**Comment by thatsjet** [comment]
> In v2 we can put the header var in a config setting so you can change this in config ui.

Sweet! I added `"header": "okhttp/3.10.0"` to the config and it's working now. Thanks folks.

**Comment by helioyanagita** [comment]
I tried adding the header to the config file but still get the same error.
Awkward. Investigating further....


Thanks,
Helio Yanagita

**Comment by furenberger** [comment]
> > In v2 we can put the header var in a config setting so you can change this in config ui.
> 
> Sweet! I added `"header": "okhttp/3.10.0"` to the config and it's working now. Thanks folks.

then its magic - that option isnt available yet.  i think you just needed a reboot :)

**Comment by bguidotti** [comment]
Mine are working for one try, then, once one of the doors changes state, they go to "No Response."
It's like they are good for one try. When I restart the HomeBridge app, they are fine again for one try. (Windows 10).
Bizarre.

**Comment by thatsjet** [comment]
> > > In v2 we can put the header var in a config setting so you can change this in config ui.
> > 
> > 
> > Sweet! I added `"header": "okhttp/3.10.0"` to the config and it's working now. Thanks folks.
> 
> then its magic - that option isnt available yet. i think you just needed a reboot :)

Well then I guess I just future proofed my config!

**Comment by iRayanKhan** [comment]
My garages were fine already. If the header section works, then heck yeah!

Re-open if this issue still persists.
