### ISSUE TITLE
Siri is reporting garage door is "closing" and "opening", instead of "closed" and "open"

### ISSUE THREAD

**Issue by desertsilver** [iRayanKhan/homebridge-chamberlain#11]
I have this plugin installed successfully (thanks!!) and want to report a minor annoyance with the implementation.  I'm not sure if this is an item to be reported with this plugin, homebridge, or HomeKit in general but when I ask Siri if the garage door is open or closed, the response is that the the garage door is "closing" instead of "closed" and "opening" instead of "open".

For instance, if the garage door is open and I ask if the garage door is closed, the response is that the garage door is "opening".  If I then ask if the garage is open, the response is again that it's "opening".

Not a major issue but the annoyance with this is that I want the confidence in knowing how Siri interpreted my request without looking at the phone.  So if I ask if the garage is open, and Siri responds that it's "opening", it could mean that Siri thinks I asked to open the garage.

Any thoughts on if this behavior can be adjusted?  Thanks

![img_0457](https://cloud.githubusercontent.com/assets/23510230/20367565/f06c058c-ac04-11e6-855d-295de2e240f5.PNG)
![img_0458](https://cloud.githubusercontent.com/assets/23510230/20367566/f08b3b50-ac04-11e6-861e-25ae16e2037a.PNG)

**Comment by caseywebdev** [comment]
If I'm understanding you correctly you're saying the door never resolves to the "Open" or "Closed" state? Are there any errors in the homebridge log?

**Comment by desertsilver** [comment]
Sorry for the confusion.  The actions are working properly.  So when I request to open/close the door, it actually happens.  This report is just for when I ask IF the door is currently open/closed.

**Comment by caseywebdev** [comment]
Ahh gotcha. I just tested it and confirmed the same result for me. My Home app says "Closed" but Siri says "Closing". It's curious that they aren't reading the same value.

**Comment by desertsilver** [comment]
Ok, at least it's not just me.  Well, if you happen to run across some configuration that might be able to "correct" this, it'd be nice but not a big deal.  Thanks for creating very useful plugin!

**Comment by caseywebdev** [comment]
When the door is closed both the current state and target state are indeed closed, which is why it puzzles me that Siri would say Closing. I'll leave this issue open in case anyone has an idea.

**Comment by desertsilver** [comment]
As an update, looks like this may have been fixed with the recent ios update since Siri is responding with "Your garage door is **_closed_**" now.

**Comment by caseywebdev** [comment]
I can confirm, I'm getting the correct verbal response now. Closing!
