### ISSUE TITLE
Anyone had luck with multiple doors and asking to open/close both/all doors at once?

### ISSUE THREAD

**Issue by gamertyke** [iRayanKhan/homebridge-chamberlain#110]
Not sure if this is a limitation of the MyQ hardware, this Homebridge plugin, or even HomeKit/Siri, but I can't seem to easily tell Siri to perform actions on both my doors at once. Is this something that could be implemented at some point?

**Comment by iRayanKhan** [comment]
Hello,
Siri interpretation is Apple related. I have two garages: one named “Single Garage”, and the second “Double Garage”. I am able to tell Siri “Hey Siri close both garages”. Then Siri does it. Hope this helps!

**Comment by gamertyke** [comment]
What’s your door hardware? I’m wondering if it’s a limitation with the MyQ hub device. I have that and 2 MyQ door sensors.

**Comment by iRayanKhan** [comment]
Mine is just an opener with MyQ built in.

**Comment by gamertyke** [comment]
I think what's going on is the MyQ hub device doesn't support the ability to simultaneously open/close the two doors. Even when clicking open on both from the home app, it doesn't work unless I wait for one door to completely finish it's task before actioning the second. Is there a flag that could be setup in the plugin to "sequence" the actions of opening/closing multiple doors?

**Comment by iRayanKhan** [comment]
I could make a flag in the plugin to add a “fake switch”, yo make an automation to close both doors. This will be in awhile due to me being busy on other plugins, but try homebridge-dummy to make a fake switch.

**Comment by iRayanKhan** [comment]
Closing; Workaround achieved.
