### ISSUE TITLE
Removal of Homekit confirmation

### ISSUE THREAD

**Issue by dinof40** [iRayanKhan/homebridge-chamberlain#114]
Hi, currently the opener requires the homekit confirmation to be confirmed on arriving home before opening the garage. This isn't convient to take your phone out your pocket when in the car, or when I'm on my motorbike etc.

I've read it's possible to remove the confirmation IF another automation automates the automation.

E.g. people use https://github.com/grover/homebridge-automation-switches/ to create a switch to a lock or door opener etc, then use homekit automation to automate this switch, which gets around the confirmation pop up as homekit doesn't know it's a lock.

Is there any way to add this functionality to your app? I'd use the switch plugin to get around this but can't work out how to use it.

**Comment by iRayanKhan** [comment]
Hey @dinof40,

Look at [this](www.a.com) plugin. 

Create a Switch in your config, call it whatever, then in the Home App, Add an automation to where when the switch turns on, It opens your garage. 

You will then be able to ask Siri "Turn on the x Switch", and it will open the garage. 

Hope this helps!

**Comment by iRayanKhan** [comment]
Closing: Workaround found.
