### ISSUE TITLE
Check status before opening

### ISSUE THREAD

**Issue by dinof40** [iRayanKhan/homebridge-chamberlain#116]
It would be great if the plugin could check door status before opening. When using Homekit automation rule to open door on returning home sometimes it doesn't recognise you're home. You wait 20 seconds it still doesn't open so you decide to manually open the door with the remote, by coincidence, the automation rule then realises you're home and attempts to open the door again. This then stops the door and then you have to manually close and open it again.

**Comment by furenberger** [comment]
Do you have a virtual switch to open the door?  I couldn't get HomeKit to open directly from a location trigger (without a prompt).   I use `homebridge-dummy` which lets me to the logic you are talking about.  https://github.com/nfarina/homebridge-dummy#readme.  I really dont think it is proper to tie the logic of timeouts and checking to a library who's purpose is to open.close a garage door.

**Comment by iRayanKhan** [comment]
Closing: This plugin is now being deprecated. Please use [this](https://github.com/hjdhjd/homebridge-myq) plugin.
