### ISSUE TITLE
No Connection

### ISSUE THREAD

**Issue by jbyhb** [iRayanKhan/homebridge-chamberlain#117]
# Explain the issue occuring:
Cannot connect to garage door through Homekit app. 

# Expected Result
Connection to garage door through Homekit app. 
Still very much connected to MyQ app, so it is not a problem with credentials.

# Info
iOS Version: 14.0
Plugin Version: 1.6.1
HomeBridge Version: 1.2.2
Node/Npm Version: 12.18.3 / 6.14.6

# Log Output:
[9/18/2020, 11:54:04 AM] [Garage Door] Error: invalid response, got HTTP 401: {"code":"401.207","message":"Unauthorized","description":"The user is locked out."}
    at /usr/local/lib/node_modules/homebridge-chamberlain/src/api.js:27:15
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by iRayanKhan** [comment]
I've been getting No Response in HomeKit too. I haven't had the chance to look at it yet, but will get back to you tomorrow.

**Comment by jbyhb** [comment]
Turning off Face or Touch ID within the MyQ app fixed this for me. Turns out the the api looks for Face or Touch ID instead of your typical login.

**Comment by iRayanKhan** [comment]
Interesting. I'll note this in the common issues page.

**Comment by tbrya** [comment]
I didn't have my Face ID on but it still gives me the same error message,

**Comment by tbrya** [comment]
Nevermind, I had to reenable then disable the Face ID.
