### ISSUE TITLE
Fetch Error

### ISSUE THREAD

**Issue by Richard0415** [iRayanKhan/homebridge-chamberlain#13]
Just installed this yesterday and it was/is working fine.  However, I just noticed this in my log file and I'm not sure what to think of it.  Note... same errors reoccurred 7 minutes after the first set (shown below).  Problem with their service perhaps?

Jan 11 06:56:45 raspberrypi homebridge[700]: [1/11/2017, 6:56:45 AM] [Garage Door] { FetchError: request to https://myqexternal.myqdevice.com/api/v4/DeviceAttribute/GetDeviceAttribute?AttributeName=doorstate&MyQDeviceId=@@@@@@@ failed, reason: getaddrinfo ENOTFOUND myqexternal.myqdevice.com myqexternal.myqdevice.com:443
Jan 11 06:56:45 raspberrypi homebridge[700]: at ClientRequest. (/usr/lib/node_modules/homebridge-chamberlain/node_modules/node-fetch/index.js:133:11)
Jan 11 06:56:45 raspberrypi homebridge[700]: at emitOne (events.js:96:13)
Jan 11 06:56:45 raspberrypi homebridge[700]: at ClientRequest.emit (events.js:188:7)
Jan 11 06:56:45 raspberrypi homebridge[700]: at TLSSocket.socketErrorListener (_http_client.js:310:9)
Jan 11 06:56:45 raspberrypi homebridge[700]: at emitOne (events.js:96:13)
Jan 11 06:56:45 raspberrypi homebridge[700]: at TLSSocket.emit (events.js:188:7)
Jan 11 06:56:45 raspberrypi homebridge[700]: at connectErrorNT (net.js:1022:8)
Jan 11 06:56:45 raspberrypi homebridge[700]: at _combinedTickCallback (internal/process/next_tick.js:74:11)
Jan 11 06:56:45 raspberrypi homebridge[700]: at process._tickCallback (internal/process/next_tick.js:98:9)
Jan 11 06:56:45 raspberrypi homebridge[700]: name: 'FetchError',
Jan 11 06:56:45 raspberrypi homebridge[700]: message: 'request to https://myqexternal.myqdevice.com/api/v4/DeviceAttribute/GetDeviceAttribute?AttributeName=doorstate&MyQDeviceId=@@@@@@@ failed, reason: getaddrinfo ENOTFOUND myqexternal.myqdevice.com myqexternal.myqdevice.com:443',
Jan 11 06:56:45 raspberrypi homebridge[700]: type: 'system',
Jan 11 06:56:45 raspberrypi homebridge[700]: errno: 'ENOTFOUND',
Jan 11 06:56:45 raspberrypi homebridge[700]: code: 'ENOTFOUND' }

**Comment by caseywebdev** [comment]
I see this too. I just assume they don't have 0-downtime deploys or something similar and occasionally drop requests. We could make the error less noisy, but it's nice to have all of the information for debugging purposes.

**Comment by Richard0415** [comment]
I don't think it's worth the effort and risk of breaking something.  Perhaps it would be if it starts happening many times a day and really cluttering up the log.  For now... I personally don't see it as an issue.  Just wanted to pass it along.  
BTW... great plugin!  Thanks for sharing your work.

**Comment by caseywebdev** [comment]
Sounds good, going to close this for now.
