### ISSUE TITLE
Plugin fails to load

### ISSUE THREAD

**Issue by Richard0415** [iRayanKhan/homebridge-chamberlain#15]
I've had the plugin installed and working properly but due to an issue with my Raspberry Pi build, I had to blow it out and start over.  Now I can't get this to load to save my life...  I've tried with 3 fresh installs - all following the Wiki (for the RaspPi3) without exception.  Here are the error's found with the plugin installed but without a config.json entry (Homebridge fails to load with the entry):

Jan 23 22:44:19 raspberrypi homebridge[2981]: [1/23/2017, 10:44:19 PM] ====================
Jan 23 22:44:19 raspberrypi homebridge[2981]: [1/23/2017, 10:44:19 PM] ERROR LOADING PLUGIN homebridge-chamberlain:
Jan 23 22:44:19 raspberrypi homebridge[2981]: [1/23/2017, 10:44:19 PM] SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
Jan 23 22:44:19 raspberrypi homebridge[2981]: at exports.runInThisContext (vm.js:53:16)
Jan 23 22:44:19 raspberrypi homebridge[2981]: at Module._compile (module.js:373:25)
Jan 23 22:44:19 raspberrypi homebridge[2981]: at Object.Module._extensions..js (module.js:416:10)
Jan 23 22:44:19 raspberrypi homebridge[2981]: at Module.load (module.js:343:32)
Jan 23 22:44:19 raspberrypi homebridge[2981]: at Function.Module._load (module.js:300:12)
Jan 23 22:44:19 raspberrypi homebridge[2981]: at Module.require (module.js:353:17)
Jan 23 22:44:19 raspberrypi homebridge[2981]: at require (internal/module.js:12:17)
Jan 23 22:44:19 raspberrypi homebridge[2981]: at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-chamberlain/src/index.js:1:92)
Jan 23 22:44:19 raspberrypi homebridge[2981]: at Module._compile (module.js:409:26)
Jan 23 22:44:19 raspberrypi homebridge[2981]: at Object.Module._extensions..js (module.js:416:10)
Jan 23 22:44:19 raspberrypi homebridge[2981]: [1/23/2017, 10:44:19 PM] ====================
Jan 23 22:44:20 raspberrypi homebridge[2981]: [1/23/2017, 10:44:20 PM] Loaded plugin: homebridge-denon

This is on a fresh OS with just the Nest and Denon Plugins installed (and working).   

Thanks!

**Comment by caseywebdev** [comment]
You'll need to upgrade to node >= 6 as the plugin uses syntax introduced in that version.
