### ISSUE TITLE
Can't disable "allow notifications" for garage door accessory

### ISSUE THREAD

**Issue by pponce** [iRayanKhan/homebridge-chamberlain#16]
For some reason i can't turn off "allow notifications" in the apple home app for my garage door.
Other accessories i can turn on and off notifications just fine. This one seems to be the only one where i can't.
When i turn the notification off for the garage door it appears to work. Toggle moves to off position. I can go back to the details page to see if it is off and it remains off in the UI. 
However when i shutdown the app and re-open it, i can see that "allow notifications" is still turned on.
Is there some option to enable or disable this that needs to be coded for?
Or is my homekit config with apple just messed up for this one accessory?

**Comment by caseywebdev** [comment]
I'm not able to reproduce this issue. That said, AFAIK homebridge does not expose any options to plugins for configuring notifications at all. I believe that's all tucked away in HomeKit and based on the device type. If you can confirm this is something the plugin can/should be accounting for let me know.

**Comment by pponce** [comment]
Will do. Thought it was strange but since it was the only accessory with the issue I though I'd ask.
I'll try to uninstall and re-install. See that fixes things.

**Comment by pponce** [comment]
An old fashioned phone reboot solved my issue.
It's rare these days that I need to to that but in this case it worked.
