### ISSUE TITLE
Requested Accessory Name Not Registered by any plugin?

### ISSUE THREAD

**Issue by jacobwtyler** [iRayanKhan/homebridge-chamberlain#17]
I'm getting this error everytime I try to load homebridge:

Feb 17 09:52:28 jacobwtyler homebridge[15428]: throw new Error("The requested accessory '" + name + "' was not registered by any plugin.");
Feb 17 09:52:28 jacobwtyler homebridge[15428]: ^
Feb 17 09:52:28 jacobwtyler homebridge[15428]: Error: The requested accessory 'Chamberlain' was not registered by any plugin.
Feb 17 09:52:28 jacobwtyler homebridge[15428]: at API.accessory (/usr/local/lib/node_modules/homebridge/lib/api.js:60:13)
Feb 17 09:52:28 jacobwtyler homebridge[15428]: at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:254:42)
Feb 17 09:52:28 jacobwtyler homebridge[15428]: at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:81:38)
Feb 17 09:52:28 jacobwtyler homebridge[15428]: at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
Feb 17 09:52:28 jacobwtyler homebridge[15428]: at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
Feb 17 09:52:28 jacobwtyler homebridge[15428]: at Module._compile (module.js:409:26)
Feb 17 09:52:28 jacobwtyler homebridge[15428]: at Object.Module._extensions..js (module.js:416:10)
Feb 17 09:52:28 jacobwtyler homebridge[15428]: at Module.load (module.js:343:32)
Feb 17 09:52:28 jacobwtyler homebridge[15428]: at Function.Module._load (module.js:300:12)
Feb 17 09:52:28 jacobwtyler homebridge[15428]: at Function.Module.runMain (module.js:441:10)
Feb 17 09:52:28 jacobwtyler homebridge[15428]: at startup (node.js:134:18)
Feb 17 09:52:28 jacobwtyler homebridge[15428]: at node.js:962:3
Feb 17 09:52:28 jacobwtyler systemd[1]: homebridge.service: main process exited, code=exited, status=1/FAILURE

**Comment by roncoejr** [comment]
I am getting the same thing.  Had been using the liftmaster2 plugin for many months, but rumor has it that Liftmaster has intentionally broken it.  Suggested resolution is to move to the Chamberlain plugin.

**Comment by caseywebdev** [comment]
What does your config look like?

**Comment by roncoejr** [comment]
All good now, @caseywebdev .  I updated my version of node **(glad I did, everything seems to run better now)** and corrected a typo in the config (I was missing an **'s'** in the word password).

Thanks for the prompt reply.

**Comment by caseywebdev** [comment]
Alright, I'm going to assume @jacobwtyler has a similar issue with their config. Closing for now.

**Comment by jacobwtyler** [comment]
Actually config was fine. 0.4.1 fixed it for me.

**Comment by jacobwtyler** [comment]
Oh I meant the new 0.4.1 of LiftMaster2 plugin.
