### ISSUE TITLE
Multiple controllable devices found error

### ISSUE THREAD

**Issue by adammascherin** [iRayanKhan/homebridge-chamberlain#24]
When I start up homebridge, I immediately get this error:

> [Garage Door] Error: Multiple controllable devices found: 1369702, 1369703, 976994
>     at getDeviceList.then.devices (/usr/local/lib/node_modules/homebridge-chamberlain/src/api.js:78:13)
>     at process._tickCallback (internal/process/next_tick.js:109:7)

But I only have 1 garage door opener. How can I fix it?

**Comment by caseywebdev** [comment]
The MyQ API seems to think you have 3 devices tied to your account. See the README about adding the deviceId field to your config and that should help you narrow down the correct id.
