### ISSUE TITLE
Unable to load homebridge using chamberlain plugin

### ISSUE THREAD

**Issue by ParabolicDestination** [iRayanKhan/homebridge-chamberlain#26]
Error: The requested accessory 'Chamberlain' was not registered by any plugin.
    at API.accessory (/Users/username/.nvm/versions/node/v4.2.4/lib/node_modules/homebridge/lib/api.js:64:13)

Added to config.json as accessory under existing accessories. 
Only fails with this plugin. 
Attempted to install plugin and uninstall plugin to see if issue was related per normal guidelines of 
npm install -g homebridge-chamberlain. 
Reverted config.json to previous version and Homebridge starts as expected. 

Had chamberlain plugin installed and working previously and then failed to recognize. Uninstalled homebridge entirely and reinstalled and was able to use all other accessories until attempting to install chamberlain plugin.

Please advise how I can resolve this issue.

**Comment by mercurylines** [comment]
I am getting the same error. were you able to find a resolution? Thanks.

**Comment by ParabolicDestination** [comment]
Yes I ended up using the Liftmaster 2 plugin instead which actually works better. It pulls the available devices from the chamberlain app so the names are automatic etc. direct from the app.

**Comment by mercurylines** [comment]
Doing this seemingly got me further along in the process, but ultimately still fails. Getting the same error as described here:
https://github.com/luisiam/homebridge-liftmaster2/issues/18

Weird stuff..

**Comment by ParabolicDestination** [comment]
Did you remove the Chamberlain plugin and line items from the json file? Also, if you check the version of Brew along with node you may need to update versions. I noticed I was out of date in that regard. I believe from the top of my head "npm -g latest” will upgrade on a mac. 
Also, this error message if exact is definitely an outdated node version. The latest is 6.4.1

**Comment by mercurylines** [comment]
I removed the chamberlain plugin and line items from config.json. Is that the json file you were referring to?

I will check the node version. Not sure what you meant by Brew- i’ve got this running on a Pi at the moment.

Thanks!


Jonathan Moore



Partner, Trifecta





149 Jefferson Street, Lexington KY 40508




[Signature Image]<http://trifectaky.com#>


T: 859.303.4663<tel:859.303.4663>



F: 859.305.1674<fax:859.305.1674>



M: 859.552.3361<tel:859.552.3361>



W: http://trifectaky.com



E: jmoore@trifectaky.com<mailto:jmoore@trifectaky.com>







[https://www.feingeist.io/fg-library/images/social_media/squares/Facebook.png]<http://www.facebook.com/trifectaky> [https://www.feingeist.io/fg-library/images/social_media/squares/Twitter.png] <http://www.twitter.com/trifectaky>  [https://www.feingeist.io/fg-library/images/social_media/squares/LinkedIn.png] <https://www.linkedin.com/in/jsmoore>  [https://www.feingeist.io/fg-library/images/social_media/squares/Google.png] <https://plus.google.com/+Trifectaky/>  [https://www.feingeist.io/fg-library/images/social_media/squares/Instagram.png] <https://www.instagram.com/trifectaky/>  [https://www.feingeist.io/fg-library/images/social_media/squares/Pinterest.png] <https://www.pinterest.com/trifectaky/>






On Sep 26, 2018, at 10:08 AM, ParabolicDestination <notifications@github.com<mailto:notifications@github.com>> wrote:

Did you remove the Chamberlain plugin and line items from the json file? Also, if you check the version of Brew along with node you may need to update versions. I noticed I was out of date in that regard. I believe from the top of my head it was "sudo n latest” on a mac.

On Sep 25, 2018, at 6:35 PM, mercurylines <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> wrote:

Doing this seemingly got me further along in the process, but ultimately still fails. Getting the same error as described here:
https://github.com/luisiam/homebridge-liftmaster2/issues/18

Weird stuff..

**Comment by ryandmiller41** [comment]
I think the solution to this is to use this code to install:

`sudo npm install -g homebridge-chamberlain`

**Comment by iRayanKhan** [comment]
Closed;
Inactive, and the solution above works since you need root permissions to access ```/usr/lib/node_modules```
