### ISSUE TITLE
Homekit status stuck on opening

### ISSUE THREAD

**Issue by rephlex00** [iRayanKhan/homebridge-chamberlain#27]
When opening the garage door using the homekit app the door opens but the button is indefinitely in the opening state until homebridge is restarted.

**Comment by GvnCampbell** [comment]
Same here... looks like something change recently that broke it.  The reporting of the door open status doesn't work.

**Comment by brandonmartinez** [comment]
After updating to the latest version of homebridge, I noticed this same issue. I'm guessing there's an incompatibility with notifications/status?

**Comment by brandonmartinez** [comment]
I think I have a fix for this; seems the API changed values. Created a pull request: https://github.com/caseywebdev/homebridge-chamberlain/pull/28

**Comment by brandonmartinez** [comment]
After some testing with the iOS App and hitting the MyQ API directly (using PostMan), I think the issue is in changes with the MyQ API, not with homebridge as I originally thought. More information can be found in the PR I just submitted: https://github.com/caseywebdev/homebridge-chamberlain/pull/29

I am running my forked branch locally on my RaspberryPi setup and it seems to be reporting as expected. Feel free to pull down and test locally as well. You should be able to run `npm install -g https://github.com/brandonmartinez/homebridge-chamberlain.git`.

**Comment by caseywebdev** [comment]
I wonder why I'm not seeing these issues...could it be different API responses based on the door model?

**Comment by brandonmartinez** [comment]
I suppose that's a possibility. Here is the result of me calling (some details obfuscated) `https://myqexternal.myqdevice.com/api/v4/UserDeviceDetails/Get?filterOn=true`:

https://gist.github.com/brandonmartinez/c6b10a1cb5dcc23bca9b2cbe1c655070

**Comment by Antheleon** [comment]
Thanks brandon. Was having the same issues and your fork seems to have solved this issue for me

**Comment by ghost** [comment]
Thanks, Brandon. Your fork fixed the issue for me as well.

**Comment by brandonmartinez** [comment]
Anyone have issues pop back up again? I'm not able to use my fixes anymore. I do wonder if the API is changing because of Chamberlain introducing the new homekit-compatible door opener. I'll have to do some network sniffing to see if that can be captured.

**Comment by Antheleon** [comment]
Yeah I think something happened today to me too. It didn’t give me any notifications when the door open/closed as usual. I’ll double check later tonight.

**Comment by ghost** [comment]
I just ran a test on mine and the fix Brandon provided is still working properly. I don't use notifications so I can't verify that.

I used HomeKit to open and close the door. I did this remotely as I have an ATV 4K in the house. Verified door movement with an IP cam. Below is the log. Lots of redundant entries for a single open/close command!

[1/12/2018, 10:05:57 AM] [Garage Door Opener] desireddoorstate changed from closed to open
[1/12/2018, 10:06:01 AM] [Garage Door Opener] doorstate changed from closed to closing
[1/12/2018, 10:06:01 AM] [Garage Door Opener] desireddoorstate changed from open to closed
[1/12/2018, 10:06:15 AM] [Garage Door Opener] doorstate changed from closing to open
[1/12/2018, 10:06:15 AM] [Garage Door Opener] desireddoorstate changed from closed to open
[1/12/2018, 10:06:21 AM] [Garage Door Opener] desireddoorstate changed from open to closed
[1/12/2018, 10:06:46 AM] [Garage Door Opener] doorstate changed from open to closed
[1/12/2018, 10:06:56 AM] [Garage Door Opener] doorstate changed from closed to closing

**Comment by brandonmartinez** [comment]
Thanks for following up! It looks like my actual unit wasn't communicating with the MyQ APIs at all. A quick power cycle and everything is back to normal.

**Comment by vpsails** [comment]
I just did a fresh install today and have the same problem where this IOS homekit app show opening until you restart the homebridge server. How would I get the latest fixes that others are mentioning here? Thanks!

**Comment by tkundhi** [comment]
I have the same issue. 
@brandonmartinez, I'm having difficulty installing your fork. Here is my command and the results. Any ideas?

$ sudo npm install -g https://github.com/brandonmartinez/homebridge-chamberlain.git

npm ERR! code 128
npm ERR! Command failed: /usr/bin/git clone -q https://github.com/brandonmartinez/homebridge-chamberlain.git /root/.npm/_cacache/tmp/git-clone-e42cc3fc
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-e42cc3fc': Permission denied
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-02-04T03_41_23_355Z-debug.log
$ 

Here is the log file.
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'https://github.com/brandonmartinez/homebridge-chamberlain.git' ]
2 info using npm@5.6.0
3 info using node@v8.9.4
4 verbose npm-session a1b89210f448e392
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData error for git+https://github.com/brandonmartinez/homebridge-chamberlain.git Command failed: /usr/bin/git clone -q https://github.com/brandonmartinez/homebridge-chamberlain.git /root/.npm/_cacache/tmp/git-clone-e42cc3fc
7 silly fetchPackageMetaData fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-e42cc3fc': Permission denied
8 verbose stack Error: Command failed: /usr/bin/git clone -q https://github.com/brandonmartinez/homebridge-chamberlain.git /root/.npm/_cacache/tmp/git-clone-e42cc3fc
8 verbose stack fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-e42cc3fc': Permission denied
8 verbose stack
8 verbose stack     at ChildProcess.exithandler (child_process.js:275:12)
8 verbose stack     at emitTwo (events.js:126:13)
8 verbose stack     at ChildProcess.emit (events.js:214:7)
8 verbose stack     at maybeClose (internal/child_process.js:925:16)
8 verbose stack     at Socket.stream.socket.on (internal/child_process.js:346:11)
8 verbose stack     at emitOne (events.js:116:13)
8 verbose stack     at Socket.emit (events.js:211:7)
8 verbose stack     at Pipe._handle.close [as _onclose] (net.js:554:12)
9 verbose cwd /var/lib/homebridge
10 verbose Linux 4.9.59-v7+
11 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "https://github.com/brandonmartinez/homebridge-chamberlain.git"
12 verbose node v8.9.4
13 verbose npm  v5.6.0
14 error code 128
15 error Command failed: /usr/bin/git clone -q https://github.com/brandonmartinez/homebridge-chamberlain.git /root/.npm/_cacache/tmp/git-clone-e42cc3fc
15 error fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-e42cc3fc': Permission denied
16 verbose exit [ 1, true ]

**Comment by csprocket777** [comment]
FYI, I just installed your fork today @brandonmartinez and it solved this issue for me. Thank you!

**Comment by josepm13** [comment]
@brandonmartinez very new here.  Just got myq working last night with homebridge using the chamberlain plug-in and having the issue described here.  Do i simply run npm install -g https://github.com/brandonmartinez/homebridge-chamberlain.git or do I need to remove the chamberlain plugin first?
Thanks.

**Comment by heypoojman** [comment]
I a new to Homebridge and I am having the same problem that is described above.  I am getting the following error when I install Brandon's forked version:
pi@raspberrypi:~ $ sudo npm install -g https://github.com/brandonmartinez/homebridge-chamberlain.git
npm ERR! code 128
npm ERR! Command failed: /usr/bin/git submodule update -q --init --recursive
npm ERR! fatal: Could not change back to '/root/.npm/_cacache/tmp/git-clone-347d3e31': Permission denied
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-07-21T04_29_08_813Z-debug.log

I would appreciate any help resolving these errors.

Thanks,
Jerry

**Comment by rotefuesse** [comment]
Hello,
me too. being very new and experienced to Raspberry Pi and programming,
I successfully did set up my homebridge and the chamberlain garage door opener plugin.
Having the same issue that the status remains in "opening" until I close the garage door again....
Trying to apply the fix (fork) from above led to the same error messages as above.

What is (can be) the cause of the "permission denied" error? 
Thank you.
Sven

**Comment by qthuan** [comment]
update the permission:
sudo chown -R $(whoami) $(npm config get prefix)/{lib/node_modules,bin,share}

hope it can help

**Comment by heypoojman** [comment]
Thanks Brandon.  Everything works now.

Instead of using the command above.  I just logged in as root and ran  npm install -g https://github.com/brandonmartinez/homebridge-chamberlain.git

**Comment by Gamer106** [comment]
Git clone https://github.com/brandonmartinez/homebridge-chamberlain.git

cd into homebridge-chamberlain

sudo npm install -g package.json

I did an npm uninstall -g homebridge-chamberlain , don’t know if it’s necessary

**Comment by jocamero** [comment]
@Gamer106 were you able to get this working?  I'm having similar issues.

**Comment by jocamero** [comment]
Got it working thanks to @brandonmartinez and his update!  Here are the details for others that have some issues:

`sudo apt-get install git` (I didn't have git installed on Raspbian Lite; this installed it)
`sudo npm install -g brandonmartinez/homebridge-chamberlain` (this installs Brandon's fork)

`systemctl restart homebridge` (restarts homebridge if you're using systemctl to auto start)

`npm ls -g --depth 0` (optional; use this to verify you have the forked version installed)

**Comment by Finch106** [comment]
Looks like homebridge-chamberlain was updated and works now, thanks again @brandonmartinez for fixing it until the update.

**Comment by johnsills1** [comment]
I’m still having problems, I cannot get the homekit to stop showing opening for the garage door. I am running the updated version of Homebridge-Chamberlain.  The weird thing is that I’ve had it working a couple of months ago and had to delete it during some troubleshooting and now I can’t get it to work right again.

**Comment by lankox** [comment]
I also started having problems with status of "opening" after this has worked perfectly for months.  The fork is no longer working for me.

**Comment by iRayanKhan** [comment]
Closed;
Inactive,
This was likely caused by an API change. The latest release fixes this issue. If this issue still occurs re-open this issue.
