### ISSUE TITLE
Craftsman Assurelink version?

### ISSUE THREAD

**Issue by Wuozopo** [iRayanKhan/homebridge-chamberlain#3]
Hi Casey

I have a Craftsman Assurelink Connectivity Hub which works great from its iPhone App.
To all intents and purposes it is identical to the MyQ Internet Gateway device.
I even tried to register it through mychamberlain but it wouldn't let me.

Compare https://assurelink.craftsman.com/ to https://www.mychamberlain.com/ and https://www.myliftmaster.com/. All the iPhone apps look identical too. Liftmaster even call it MyQ.

I already tried your plugin and edited my config.json for it and tested. It all works great, including logging in (I created a MyQ account to test) but as there is no device registered on that account I can go no further.

I have homebridge running on a Raspberry Pi, and homebridge-zway on another.
I would like to incorporate the garage door and was excited to find your plugin which means it should be possible. I'd have a crack at it myself but my programming skills are based elsewhere!

Regards, Ian.
Houston, TX

**Comment by caseywebdev** [comment]
Haha wow those sites are identical! It does seem like they would probably operate similarly.

Do you happen to know what API the phone app hits? I used https://mitmproxy.org to sniff out the requests MyQ was sending (https://myqexternal.myqdevice.com) and that's why that is hardcoded in `api.js`. The best case is that Assurelink follows the same API and is just hosted at a different URL. We could trivially make the API URL a config option and you'd be good to go!

**Comment by Wuozopo** [comment]
If I knew where to start with mitmproxy I'd probably do so. Unfortunately I'm a Windows user on the whole, my (real) Unix days were many years ago and as such I am only tinkering with the Pi based stuff.
I'm sure with some more detailed direction I could achieve something.

**Comment by caseywebdev** [comment]
I work almost exclusively on *nix systems so I can't help you there. If you're able to find out the requests your phone is making to the assurelink API I bet it wouldn't be too hard to integrate it into the existing code. I'm sure someone has solved this problem for Windows before.

**Comment by Wuozopo** [comment]
I'm still looking into it. I might just get a MyQ gateway as they apparently work with Craftsman openers anyway. Lot of stuff on Smart Things forum about this.
I'll let you know if/when I find anything regarding the Craftsman API.

**Comment by Wuozopo** [comment]
I've replaced the Craftsman/Assurelink Gateway with the Chamberlain MyQ version. Removed configuration from the Assurelink account, then set it up using MyQ, no problems. There is more functionality in the MyQ iOS App for starters, including Touch ID.
I've updated your plugin to 1.0.1 and everything seems to be working great.
So it's not worth doing an Assurelink version in my view.

**Comment by caseywebdev** [comment]
Glad to hear it's all working well for you!
