### ISSUE TITLE
Compatibility Issue?

### ISSUE THREAD

**Issue by vpsails** [iRayanKhan/homebridge-chamberlain#30]
I've been trying for a couple of days to get my rpi3 back up and running. I've installed node, homebridge, the homebridge plugin for homebridge-chamberlain along with the config.json file as outlined but I continue to run into the following error:

[2018-2-1 22:30:12] Loaded plugin: homebridge-chamberlain
[2018-2-1 22:30:12] Registering accessory 'homebridge-chamberlain.Chamberlain'
[2018-2-1 22:30:12] ---
/usr/lib/node_modules/homebridge/lib/server.js:212
  var username = config.bridge.username;
                               ^

TypeError: Cannot read property 'username' of undefined

Any ideas what may be wrong. I've done the install a dozen times but nothing seems to work.. I'm using Raspian stretch. Thanks!!

**Comment by caseywebdev** [comment]
This looks like it could be an issue with your config file. If you share it (obviously hide any private info) we can probably figure it out.

**Comment by vpsails** [comment]
Agreed... I'm a noob at this. Got it working last time through some great online instructions but this time through the old instructions on website were taken down and now I'm stuck. rpi3 memory card blew up and I'm without a clue.

 I'm pretty sure you're correct that the config file is incomplete and, quite honestly, there isn't a lot of good info out there as to how to do a complete homebridge config file creation. Would you happen to have a complete sample of everything that needs to be in the config file? I know that many of the plugins provide the "accessories" or "platform" section of the config file but where do I get the rest of the fields and data that are required to be inserted? Thus far I have been using the following...

{
	"accessory": "Chamberlain",
	"name": "Garage Door",
	"username": "your mychamberlain.com email",
	"password": "your mychamberlain.com password"
}
I'm replacing the username and password with my Chamberlain login info but that is it. What else do I need? Thanks!!

**Comment by vpsails** [comment]
I finally figured out what my problems with the config file were... Thanks!
