### ISSUE TITLE
Feature Suggestion - For Your Consideration

### ISSUE THREAD

**Issue by jvmahon** [iRayanKhan/homebridge-chamberlain#31]
One feature I would love to have is the ability to set an automation so that my doors can automatically open / close when I drive up to the garage or leave. As I'm sure you know, HomeKit doesn't allow this for devices like Garage Door Openers as you need to confirm their operation.

I think this could be achieved, however, by implementing the Garage Door Opener as a "Switch" HAP service with an On characteristic instead of the "TargetDoorState."  I was hoping I could do this myself, but the code is pretty complex. I expect the code would need to be able to map garage door states like opening / closing to a simple On/Off. Would you consider implementing a change like this as a separate fork / project? If not, thoughts on whether this is achievable and any guidance on what you think would be needed to do this?  Thanks!

**Comment by caseywebdev** [comment]
> One feature I would love to have is the ability to set an automation so that my doors can automatically open / close when I drive up to the garage or leave.

You have more faith in the location technology than I do 😉 but it's definitely a cool idea. I, too, have run into the annoying fact that you can't even lock/close, let alone unlock/open "security" devices like locks or doors.

> I think this could be achieved, however, by implementing the Garage Door Opener as a "Switch" HAP service with an On characteristic instead of the "TargetDoorState."

Yup this would certainly bypass the "security" device restriction. I think you're on the right track. You can probably get away with just changing [this section](https://github.com/caseywebdev/homebridge-chamberlain/blob/17c377a32a12cf47fbd6f4cdd5c803b6bb98ca3f/src/chamberlain-accessory.js#L9-L61) to use `Switch`/`On`/`Off` terminology where appropriate as opposed to the `Door`/`Open`/`Close`. The list of possible characteristics and services are available [here](https://github.com/KhaosT/HAP-NodeJS/blob/1f1fea7a995f09671d5e0aba50e965c1f4729f4d/lib/gen/HomeKitTypes.js).

**Comment by zebzbranek** [comment]
I would like to control my Chamberlain/Liftmaster gate with homekit. I have the MyQ Bridge and have my two garage doors and switches that are all homekit active. In talking to Chamberlain tech support, I am uncertain their gate will ever be homekit compatible. With the Raspberry Pi, I have successfully connect my Nest, Wemo and Eco Plug. What can I do? I would like to say "open gate," or "close gate." How can I add my gate to my config.json file?

**Comment by iRayanKhan** [comment]
Closed; Inactive.
If I understand correctly, you could just make a switch to toggle when you are home a plugin called
```homebridge-dummy``` seems to work well as I use it on my Lamps.
