### ISSUE TITLE
Chamberlain MyQ and Craftsman

### ISSUE THREAD

**Issue by ldhall1856** [iRayanKhan/homebridge-chamberlain#32]
Hi,

I have a craftsman WIFI garage door I was wondering since chamberland and craftsman are owned by the same company and use the same style IOS app could i get it working on a craftsman garage door.

I'm very new to this so please forgive my ignorants.

**Comment by iRayanKhan** [comment]
Closed;
Inactive.
I have a lift master garage and this plugin works great, they all seem to share the same API so it should work.
