### ISSUE TITLE
One garage door, but plugin detects 2 device IDs and throws error

### ISSUE THREAD

**Issue by LaChrome** [iRayanKhan/homebridge-chamberlain#33]
I only have one garage door, but this plugin detects two device Ids. Throws an error on startup with the default config:

[Garage Door] Error: Multiple controllable devices found: 4355369, 4355368
    at getDeviceList.then.devices (/usr/local/lib/node_modules/homebridge-chamberlain/src/api.js:78:13)
    at process._tickCallback (internal/process/next_tick.js:103:7)

Within the online Chamberlain account, only one garage door is configured, and only one is shown.

So I then manually add both device IDs to the config, and it starts up fine - Homekit now shows two garage doors, one works fine, the other does nothing.

The part number of the Chamberlain unit is: 050DCTWF
Listed on Lowes website as a "B970C" (Chamberlain 1.25-HP Whisper Drive Belt)

Weird issue. Manually removed the non-functioning garage accessory from showing in 'favourites'.

**Comment by caseywebdev** [comment]
You can just remove the device ID that's not in use from your config. That error is thrown when more than one device that's not the gateway itself is returned from the API. Since the API is undocumented, I can't really tell you what the other device ID is for, so just use trial and error to get the garage door opener ID and only use that one.

**Comment by ayd10** [comment]
I'm also getting an error saying multiple controller devices found, but only have one garage door added in the config file without a "deviceID" tag. Any idea how I fix this? I

**Comment by shawnstrickland** [comment]
> I'm also getting an error saying multiple controller devices found, but only have one garage door added in the config file without a "deviceID" tag. Any idea how I fix this? I

If you get an error about multiple devices but only have one, you'll have to see which one "works" as far as setting it up and testing it out, and then only keeping that deviceId for one garage door accessory. I can confirm this works as my account is replying with 4 devices but I only have two doors. Putting one deviceId (the right one, another is a byproduct of an unauthorized API) in the accessories lets me control one door just fine.

**Comment by vipulgarg5** [comment]
Where do you find the device id's. I have two garage doors but don't see the device id.

**Comment by iRayanKhan** [comment]
@vipulgarg5 Running HomeBridge with no device id’s in your config, spits out the device ID’s. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
