### ISSUE TITLE
Report/response delay

### ISSUE THREAD

**Issue by Magiccowinuse** [iRayanKhan/homebridge-chamberlain#34]
Is there a line I can change to lengthen the delay of Siri's report back when closing the garage door? Siri seems to report too quickly, giving a confused reply by Siri stating the door is _still_ opening/closing. When, if the report just came 2 seconds later on each attempt, she would report a successful operation.

**Comment by iRayanKhan** [comment]
Closed; 
Inactive.
If I am understanding correctly, your issue is that Siri replies too fast on the status?
If the garage is closing and you ask Siri right when you chose to close it if it's closed, it'll still say it ins't closed since it isn't 100%.
