### ISSUE TITLE
doest work for me anymore

### ISSUE THREAD

**Issue by menmi03** [iRayanKhan/homebridge-chamberlain#35]
This was working for a long time, then recently (within the last week) I get this, repeatedly, over and over.... 

[2018-6-3 23:48:12] [House Side Garage Door] Error: Error processing request (217)
at fetch.then.then.data (/usr/local/lib/node_modules/homebridge-chamberlain/src/api.js:26:29)
at <anonymous>
at process._tickCallback (internal/process/next_tick.js:118:7)

Thanks if anyone can look into it.  I've tried reloading, removing accessories and let it error out(thinking maybe my deviceIDs changed) nothing.  Just will not work anymore.

**Comment by shahavinas** [comment]
I too am facing the same issue. Not sure how to fix it.

**Comment by caseywebdev** [comment]
```
Mon Jun 04 2018 11:52:01 AM - Error: Error processing request (217)
Mon Jun 04 2018 11:53:11 AM - FetchError: invalid json response body at https://myqexternal.myqdevice.com/api/v4/DeviceAttribute/GetDeviceAttribute?AttributeName=doorstate&MyQDeviceId=xxx reason: Unexpected token < in JSON at position 0
```

I get these two errors sporadically (I assume because they're rolling their API servers) but it always settles back down.

**Comment by mattwillems-lr** [comment]
I get Error processing request (217) every 10 seconds no matter what. It shows up once as homebridge starts up and never stops. Chamberlain device is not detected.

`[2018-10-3 08:12:41] [Garage Door] Error: Error processing request (217)
    at fetch.then.then.data (/usr/lib/node_modules/homebridge-chamberlain/src/api.js:26:29)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)`
