### ISSUE TITLE
Will this work with the "MyQ Smart Home Starter Kit (830REV)"?

### ISSUE THREAD

**Issue by prutsky** [iRayanKhan/homebridge-chamberlain#36]
I installed this plugin but in my "Home" app on my iPhone I see the Garagedoor (+ icon), but it also says "updating" below it. (or in Dutch: "Bijwerken...").
So I'm unable to control the door via the Home app, nor Siri.
What is wrong?

**Comment by iRayanKhan** [comment]
Closed; 
Inactive.
If it's polling the updating status it doesn't seem to be able to reach your home hub, or the garage.
