### ISSUE TITLE
Invalid Json

### ISSUE THREAD

**Issue by sohnkarlsruhe** [iRayanKhan/homebridge-chamberlain#37]
i get this error with the standard configuration like

`{
  "accessory": "Chamberlain",
  "name": "Garage Door",
  "username": "your mychamberlain.com email",
  "password": "your mychamberlain.com password"
}`

`[9/20/2018, 12:51:38 PM] [Garagentor hinten] { FetchError: invalid json response body at https://myqexternal.myqdevice.com/api/v4/User/Validate reason: Unexpected token < in JSON at position 0
    at /opt/node/lib/node_modules/homebridge-chamberlain/node_modules/node-fetch/lib/body.js:48:31
    at process._tickCallback (internal/process/next_tick.js:109:7)
  name: 'FetchError',
  message: 'invalid json response body at https://myqexternal.myqdevice.com/api/v4/User/Validate reason: Unexpected token < in JSON at position 0',
  type: 'invalid-json' }
`

the config.json file is valid, there is no other plugin in the file.

what can i do?

**Comment by caseywebdev** [comment]
This is the MyQ API returning invalid JSON (probably HTML) and not related to your config JSON. Are you getting this intermittently or all the time? I see this message often, I believe the MyQ API is not the most reliable service but it's unavoidable.

**Comment by sohnkarlsruhe** [comment]
I get it Evers 5 seconds. The Garage door is offline in the Home App. With the myq app it works fine

**Comment by sohnkarlsruhe** [comment]
Now it works.. i do nothing
