### ISSUE TITLE
Getting the following error, but everyting appears to be working

### ISSUE THREAD

**Issue by jvward** [iRayanKhan/homebridge-chamberlain#38]
Everytime I open or close my garage door I get the following error:

 Error: Error processing request (217)
    at fetch.then.then.data (/usr/lib/node_modules/homebridge-chamberlain/src/api.js:26:29)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)

Everything appears to be working ok, I just keep seeing this in homebridge.  I was wondering if anyone had seen this before? or if there is a way to fix it?

**Comment by ghost** [comment]
Seeing the same thing. Also wondering if there's a fix.

**Comment by caseywebdev** [comment]
Requests to the MyQ API regularly fail and there's not much we can do about that. I think suppressing this error would be worse.

**Comment by setheryb** [comment]
I get this error, but nothing works.

**Comment by SmallwoodDR82** [comment]
what's the reason for the failure? server issues on Chamberlain side? Is the API requesting too often?

**Comment by iRayanKhan** [comment]
Closed;
Inactive.
It just seems like a warning since it doesn't affect anything.
