### ISSUE TITLE
Why? Just use liftmaster plugin....

### ISSUE THREAD

**Issue by AppleTechy** [iRayanKhan/homebridge-chamberlain#4]
Chamberlain and Liftmaster connect to the exact same MYQ servers....
It would be better to make a pull request of that plugin rather than creating an entire new plugin.. There have been I think 3 other plugins other than the Liftmaster Plugin, that have since been published that are less stable and it's confusing users on which one to download.

**Comment by caseywebdev** [comment]
I had issues with the liftmaster plugin so I wrote this primarily for myself to address those issues while also learning the homebridge plugin interface. I think people should use whichever plugin works best for them.
