### ISSUE TITLE
'Closed' Notifications Not Always Received

### ISSUE THREAD

**Issue by twentyNoise** [iRayanKhan/homebridge-chamberlain#40]
Hi,

About 60% of the time the plugin works great. The other 40% I have noticed that I will get a "Garage Door Opened" notification, but I won't receive a "Garage Door Closed" notification. Then, upon opening the Home App on my phone I immediately receive a "Garage Door Closed" notification. This immediate notification could come hours later - when I haven't opened the Home app for a while. I notice that when I do finally open the Home app I see the Garage Door Homebridge icon briefly in an "Opening" state, which then quickly turns to "Closed" - and then I receive the "Garage Door Closed" notification.

Any ideas what could be causing this?

Thanks

--- Update ---

After investigating this further, the Log file shows that the Garage Door is opened, closed etc. but I'm not consistently receiving the 'Closed' notifications on some devices. I always see the 'Open' notifications.

My iPhone is consistently the device that's NOT receiving the Closed notifications. But the devices that I leave at home like my iPad had been receiving them - not sure if it receives them 100% of the time though. I'm wondering if it could be some sort of Cellular Network / Wifi issue? But I don't have this problem with any other devices. That is, if I set up a device to receive notifications - I get them wherever and on whichever device I'm using.

As you can see below, the log shows the opening and closing, but the Garage Door Closed Notification from HomeKit is not always received on my iPhone.

[12/30/2018, 2:40:56 PM] [Garage Door] doorstate changed from closed to opening
[12/30/2018, 2:40:56 PM] [Garage Door] desireddoorstate changed from closed to open
[12/30/2018, 2:41:08 PM] [Garage Door] doorstate changed from opening to open
[12/30/2018, 2:46:02 PM] [Garage Door] desireddoorstate changed from open to closed
[12/30/2018, 2:46:12 PM] [Garage Door] doorstate changed from open to closing
[12/30/2018, 2:46:26 PM] [Garage Door] doorstate changed from closing to closed

Any ideas? Or ideas on how to troubleshoot further?

Thanks!

**Comment by iRayanKhan** [comment]
Closed;
Inactive.
The plugin doesn't control the notifications aspect. When the open/closed state is reported, HomeKit will send the notification. And since everyone else gets the notification it may be a homehub/iCloud issue.
