### ISSUE TITLE
Not Responding

### ISSUE THREAD

**Issue by johnsills1** [iRayanKhan/homebridge-chamberlain#41]
I recently upgraded to Node.js 8 and now the homebridge-chamberlain doesn't work anymore. My device is not responding. It was working when I had Node.js v4 installed by itself, once I upgraded, it stopped. Is this not compatible with node.js 6 or 8?

**Comment by iRayanKhan** [comment]
Closed; Inactive.
The plugin works on the latest version of Node, something in your install may have broken. Try updating the plugin too.
