### ISSUE TITLE
Queries to myqexternal.myqdevice.com

### ISSUE THREAD

**Issue by bartenderck** [iRayanKhan/homebridge-chamberlain#42]
Is there any way to change the query interval time to myqexternal.myqdevice.com?  Mine currently seems to check the status every 10 seconds.

**Comment by caseywebdev** [comment]
It's hardcoded [here](https://github.com/caseywebdev/homebridge-chamberlain/blob/41fc2fb20357bcc977445efab81a22b9a828cc41/src/chamberlain-accessory.js#L6) (in milliseconds). When the door is opening/closing the poll interval is 2 seconds. MyQ doesn't have a push API that I know of and this is the same interval they use on their own web app, so I don't want to exceed that.

**Comment by bartenderck** [comment]
Thanks for the quick response.  Is this something I can manually edit or would the entire package need to be compiled?


-Craig

**Comment by caseywebdev** [comment]
You can manually edit the `homebridge-chamberlain/src/chamberlain-accessory.js` file saved in your `node_modules` folder (location depends on how you installed) and restart homebridge. I wouldn't recommend lowering this value though. If they see you're hitting the API too frequently they could decide to block your IP 🤷‍♂️

**Comment by bartenderck** [comment]
Thanks!  I actually want to increase the time so it queries less often. 


-Craig
