### ISSUE TITLE
Unauthorized (216)

### ISSUE THREAD

**Issue by usmcguy** [iRayanKhan/homebridge-chamberlain#43]
Performed an update to the latest package. No longer able to use. Error in log:

`[Garage Door] Error: Unauthorized (216)
    at fetch.then.then.data (/usr/local/lib/node_modules/homebridge-chamberlain/src/api.js:26:29)
    at process._tickCallback (internal/process/next_tick.js:68:7)`

I completely reset homebridge, deleted accessories and persist folders, re-added to homekit. However, 216 error still appears in log.

**Comment by iRayanKhan** [comment]
@usmcguy Try the latest version that was published earlier today, it fixed an API change. In the future past your config.json file just incase.

**Comment by bkalai321** [comment]
getting the same error
