### ISSUE TITLE
Can this be used without internet connection?

### ISSUE THREAD

**Issue by gittalicious** [iRayanKhan/homebridge-chamberlain#47]
I have this set up and working, but I would love to be able to use the myQ openers without having every command go through Chamberlain's internet servers. Is this possible? I have tried blocking internet access for the MyQ hub on my router, but then the accessory becomes unresponsive. Is there a way to get this working without involving the internet servers?

**Comment by caseywebdev** [comment]
Nope, not possible with the MyQ setup. I’ve actually stopped using MyQ for this reason and wired up a raspberry pi to my spare clicker to open/close the door without internet.

**Comment by gittalicious** [comment]
Can you point me to any tutorials that would explain how to do that?

**Comment by caseywebdev** [comment]
Something like https://coderwall.com/p/jsd5mw/raspberry-pi-garage-door-opener-with-garagepi is pretty much what I ended up doing. Good luck 👍🏻
