### ISSUE TITLE
Looks like they are messing with the protocol again

### ISSUE THREAD

**Issue by mckinleytabor** [iRayanKhan/homebridge-chamberlain#49]
This morning I'm getting an error: 

'invalid json response body at https://myqexternal.myqdevice.com/api/v4/User/Validate reason: Unexpected token < in JSON at position 0'

I'm investigating, but I wanted to leave this here to let people know... it's not just you.. :p

**Comment by mckinleytabor** [comment]
...and here's the fix, it looks like they (chamberlain, myq, liftmaster, whoever) has deprecated the Application ID being used in this project.

in the ./src/api.js file, line 6, you'll find a string:
NWknvuBd7LoFHfXmKNMBcgajXtZEgKUh4V7WNzMidrpUUluDpVYVZx+xT4PCM5Kx

This is the old deprecated Application ID for "chamberlain", thankfully, it looks like the programmers for that company are lazy and they are consolidating all the apps under one label.

If you replace the above string in ./src/api.js line 6 with:
Vj8pQggXLhLy0WHahglCD4N1nAkkXQtGYpq2HrHD7H1nvmbT55KqtN6RSF4ILB/i

it should start working again.

--noob--
The ./src/api.js file should be located in your node_modules directory, whose location will be slightly different depending on platform (mac, pc, raspberry pi, etc), and if you used the "global" flag (-g) when installing the homebridge-chamberlain node package with npm. On the Raspberry Pi with the -g flag it's located at /usr/lib/node_modules/homebridge-chamberlain/erc/api.js. Basically is you looks around for "homebridge-chamberlain/erc/api.js" you'll find it on your system.

Change line 6 as describe above and restart homebridge and it _should_ work. 
--/end noob--

Of course these guys could come back at any time and deprecate this Application ID as well, so I'll be keeping an I on it. Fortunately though it looks like they have not deperacted the the whole 4.1 API.  But whatever, it's always going to be a game of cat and mouse.  ¯\_(ツ)_/¯

**Comment by romkey** [comment]
Thank you! Worked great, you just saved me a lot of grief :)

**Comment by caseywebdev** [comment]
Released in `1.0.4`
