### ISSUE TITLE
Filter out gateways and select single garage door device when deviceId not specified in config.json 

### ISSUE THREAD

**Issue by russmo** [iRayanKhan/homebridge-chamberlain#59]
In order to make this plugin "just work" with minimal effort and configuration by users with a single garage door, consider filtering gateway devices from garage doors or other controllable devices.  The devices list from MyQ api v5 is returning doors/openers as well as gateway devices such as the Liftmaster or Chamberlain wired MyQ internet gateway (model 828LM or CIGBU)  Two things come to mind:

1. When homebridge loads this plugin with a config.json missing a DeviceId field and multiple devices are returned, this plugin prints out a warning that multiple devices are present and lists their ids.  It would be helpful to list in that warning the device-types for those ids (e,g., "gateway"/"ethernetgateway" vs "garagedoor"/"garagedooropener".  This would help users put the correct one for their garage door in the config.json accessory definition.
2. If only one device is returned for the specified account, attempt to use that one device.  If only one "garagedoor"/"garagedooropener" device is present, attempt to use that device even if one or more "gateway" devices are present.

**Comment by russmo** [comment]
Here is the JSON returned when I queried the MyQ V5 API with curl on the command line.  Pretty easy to pick off the "device_family": "gateway" / "device_type": "ethernetgateway" as compared to the  "device_family": "garagedoor" / "device_type": "garagedooropener".

```
{
  "href": "http://api.myqdevice.com/api/v5/accounts/XXXXXXX/devices",
  "count": 2,
  "items": [
    {
      "href": "http://api.myqdevice.com/api/v5/accounts/XXXXXXX/devices/GW00000XXXXX",
      "serial_number": "GW00000XXXXX",
      "device_family": "gateway",
      "device_platform": "myq",
      "device_type": "ethernetgateway",
      "name": "My Hub",
      "created_date": "2018-03-26T01:14:25.807",
      "state": {
        "firmware_version": "4.2",
        "homekit_capable": false,
        "homekit_enabled": false,
        "learn": "http://api.myqdevice.com/api/v5/accounts/XXXXXXX/devices/GW00000XXXXX/learn",
        "learn_mode": false,
        "updated_date": "2019-10-22T05:18:16.5459703Z",
        "physical_devices": [],
        "pending_bootload_abandoned": false,
        "online": true,
        "last_status": "2019-10-22T05:18:16.5459703Z"
      }
    },
    {
      "href": "http://api.myqdevice.com/api/v5/accounts/XXXXXXX/devices/CG0XXXXXXXXX",
      "serial_number": "CG0XXXXXXXXX",
      "device_family": "garagedoor",
      "device_platform": "myq",
      "device_type": "garagedooropener",
      "name": "Garage",
      "parent_device": "http://api.myqdevice.com/api/v5/accounts/XXXXXXX/devices/GW00000XXXXX",
      "parent_device_id": "GW00000XXXXX",
      "created_date": "2018-11-03T00:26:35.933",
      "state": {
        "gdo_lock_connected": false,
        "attached_work_light_error_present": false,
        "door_state": "closed",
        "open": "http://api.myqdevice.com/api/v5/accounts/XXXXX/devices/CG0XXXXXXXXX/open",
        "close": "http://api.myqdevice.com/api/v5/accounts/XXXXXXX/devices/CG0XXXXXXXXX/close",
        "last_update": "2019-10-22T03:54:11.8069727Z",
        "passthrough_interval": "00:00:00",
        "door_ajar_interval": "00:00:00",
        "invalid_credential_window": "00:00:00",
        "invalid_shutout_period": "00:00:00",
        "is_unattended_open_allowed": true,
        "is_unattended_close_allowed": true,
        "aux_relay_delay": "00:00:00",
        "use_aux_relay": false,
        "aux_relay_behavior": "None",
        "rex_fires_door": false,
        "command_channel_report_status": false,
        "control_from_browser": false,
        "report_forced": false,
        "report_ajar": false,
        "max_invalid_attempts": 0,
        "online": true,
        "last_status": "2019-10-22T05:18:16.5459703Z"
      }
    }
  ]
}
```

**Comment by iRayanKhan** [comment]
Great detail, time to investigate this.
>If only one device is returned for the specified account, attempt to use that one device. If only one "garagedoor"/"garagedooropener" device is present, attempt to use that device even if one or more "gateway" devices are present.
>
This used to be the case in the V4api Branch since it didn't detect the ethernet gateways.

I made a fork called "test" which may alleviate this issue. I haven't tested the branch yet locally so you can do it at your own will (It hasn't been verified to even run yet), but I will run it tomorrow when I get home. If that fork does work, I'll conduct more testing then merge it into the main branch.

**Comment by russmo** [comment]
test branch works fine for me whether I specify the deviceId for my one garage door or remove that parameter from config.json.

**Comment by iRayanKhan** [comment]
@russmo I can't believe I kept saying fork instead of branch. So to confirm, does it filter the device out and no longer crash the instance?

**Comment by iRayanKhan** [comment]
Closing this issue; adding this fix to the backlog and will work on it. 
Thanks for reporting it, and giving lots of info about the gateway ID. Will have it patched ASAP.
