### ISSUE TITLE
HTTP 401 - Security Token Expired

### ISSUE THREAD

**Issue by AdamSnow** [iRayanKhan/homebridge-chamberlain#60]
Garage Doors not responding in Homekit anymore. Just did the update to the new API and it worked for a couple of days, but now both door openers are giving the same error.

# Info
Plugin Version: 1.0.5
HomeBridge Version: 0.4.50

# Log Output:
Error: invalid response, got HTTP 401: {"code":"401.101","message":"Unauthorized","description":"The Security Token has expired."}
    at res.text.then.body (/homebridge/node_modules/homebridge-chamberlain/src/api.js:27:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by iRayanKhan** [comment]
Have you tried making a new bridge or remove your Garages from HomeKit and remove deviceID's from the config? Many people have reported their ID's changing.

**Comment by coneslayer** [comment]
This happened to me today as well. Restarting homebridge "fixed" it, but I would guess that this response needs to be caught, and the username/password login needs to be repeated to get a new security token.

**Comment by iRayanKhan** [comment]
@coneslayer thank you for verifying that this works, going to advise people to do this.

**Comment by AdamSnow** [comment]
> This happened to me today as well. Restarting homebridge "fixed" it, but I would guess that this response needs to be caught, and the username/password login needs to be repeated to get a new security token.

Rebooting does appear to fix it. Should have tried that from the beginning. Thanks for the help!

**Comment by iRayanKhan** [comment]
Anytime, glad to be tackling this issue.

**Comment by coneslayer** [comment]
IMHO this is still a bug and should remain open. The security token expired error should be caught and a new token should be requested via the API by sending the username and password again.

**Comment by AdamSnow** [comment]
I agree with that thought. Re-opened.

**Comment by iRayanKhan** [comment]
@coneslayer It was caught back in ```V0.0.15``` on September 27th 2016.
I guess since the API has been refreshing a lot it seems to have changed. I'm going to look back on the SC and see how to implement it properly in the newly V5 Api. 

I am not too familiar with the tokens and API, but I don't know if the API can see if it has expired. Maybe I can see if it spits out that error, to re-login to the API as your fix mentioned or a restart.

**Comment by iRayanKhan** [comment]
Closing this issue; adding this fix to the backlog and will work on it. 

Thanks for reporting this y'all, I will do more investigating and hopefully V1.0.7 should fix this or 1.0.8

**Comment by russmo** [comment]
Just confirming that this shows up on my end after running for about two days on the the 1.0.5 release.  Not sure that issues like this should be closed for bugs that break the current release until they are addressed by real code fixes.  It makes it seem that this issue has been addressed and is no longer affecting the code base.  As it stands, anyone that uses release 1.0.5 is going to have to restart homebridge on a regular basis.  My guess is that if I restart homebridge now, this bug will pop up again in a day or two and prevent use my garage through homebridge.

[10/26/2019, 7:08:57 AM] [Garage] Error: invalid response, got HTTP 401: {"code":"401.101","message":"Unauthorized","description":"The Security Token has expired."}                     
    at res.text.then.body (/usr/local/lib/node_modules/homebridge-chamberlain/src/api.js:27:15)                                                                                          
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by iRayanKhan** [comment]
I’ll re open it then, but this is a one time issue to seems since there has been a big difference in the V4 and V5 API’s. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by coneslayer** [comment]
I'm testing this simple change, but it will be a couple of days before I know if it works...
```
--- a/src/api.js
+++ b/src/api.js
@@ -109,7 +109,7 @@ module.exports = class {

   maybeRetry(fn) {
     return fn().catch(er => {
-      if (er.message.indexOf('Please login again') === -1) throw er;
+      if (er.message.indexOf('Security Token has expired') === -1) throw er;

       this.options = _.omit(this.options, 'SecurityToken');
       return fn();
```

**Comment by iRayanKhan** [comment]
By chance does anyone have an expired security token still willing to test @coneslayer's fix? I'm making a branch called ```development``` with the changes in about 8 hours. As of right now it's even with master.

**Comment by longrass** [comment]
Have we got a fix yet team? I’m having to reboot homebridge twice a day now!

**Comment by coneslayer** [comment]
I've had homebridge running continuously for about 5 days with no problems, with the `Security Token has expired` change above, plus a `User-Agent` change similar to [this one](https://github.com/caseywebdev/homebridge-chamberlain/commit/07ca9bd30eb2d37a87780a6a4150a03cb73bc0a1) (that change hadn't been committed yet when I was last troubleshooting).

**Comment by longrass** [comment]
> I've had homebridge running continuously for about 5 days with no problems, with the `Security Token has expired` change above, plus a `User-Agent` change similar to [this one](https://github.com/caseywebdev/homebridge-chamberlain/commit/07ca9bd30eb2d37a87780a6a4150a03cb73bc0a1) (that change hadn't been committed yet when I was last troubleshooting).

I’m a noob with this stuff, would you mind explaining to me please what steps I can take to resolve it?

**Comment by iRayanKhan** [comment]
I'll update the development branch with those changes tonight, if anyone would be kind enough to test it out, I'd appreciate it. I personally still use the V4 Api (4 versions behind) and it still works for me.

**Comment by nebduj** [comment]
I manually changed the code in my pi to match coneslayer's change and restarted homebridge.  Began working immediately.  My pi hadn't worked even after restarting it previously.

**Comment by iRayanKhan** [comment]
Can anyone validate this for me?
https://github.com/caseywebdev/homebridge-chamberlain/pull/72

**Comment by coneslayer** [comment]
@iRayanKhan I've just installed the `development` branch and it's working fine for me, but it will probably take a couple of days (48 hours?) to be confident that the expired security token fix is working.

**Comment by longrass** [comment]
Can anyone help me
With what I need to do please?

**Comment by iRayanKhan** [comment]
To do this just clone the dev branch and paste the changed files over, or manually edit them. I'll merge this branch/Pull in tonight so it'll just be a simple ```sudo npm I -g homebridge-chamberlain```

**Comment by iRayanKhan** [comment]
I’ll merge the pull in today so everyone can use it. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by iRayanKhan** [comment]
I just published the patch and all should be good now, if anything else arrises re-open this issue.
