### ISSUE TITLE
Shows at ‘Not Responding’ in home app

### ISSUE THREAD

**Issue by schmidt660** [iRayanKhan/homebridge-chamberlain#61]
Started about a week ago, HomeKit (home app) shows as ‘not responding’ yet works fine in chamberlain app. Also shows correct status in homebridge admin page under accessories. 

Other homebridge plugin (for LG webos tv) working fine via homebridge in home app, so just just an issue with this.

**Comment by iRayanKhan** [comment]
@schmidt660 Few questions:
1) Does it work with Siri Still?
2) Can any other devices control the Garage?
3) Is the plugin updated and on the latest version?
4) What iOS version is your device on?

**Comment by schmidt660** [comment]
Nope stopped working with Siri as well. The chamberlain myq app still works fine. The plugin is up to date (just checked again). Devices are all on latest iOS 13.1.3

**Comment by iRayanKhan** [comment]
Are you using docker? Also can you run HomeBridge with the Home App closed, then open it and try to control it. The logs should state the error when the Home app requests a Status Update. Also do you mind pasting your config.json file? Make sure to remove all personal info. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by schmidt660** [comment]
Yeah using docker. Just checked logs and it’s saying error multiple devices found? Weird I only have garage door!

**Comment by schmidt660** [comment]
[10/24/2019, 7:30:13 PM] [Garage Door] Error: Multiple controllable devices found: CGxxxxxx, GWxxxx
    at /homebridge/node_modules/homebridge-chamberlain/src/api.js:106:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

Edited by iRayanKhan:
Removed DeviceID’s so no one can try it.

**Comment by iRayanKhan** [comment]
I made a branch called “test” to fix the Multiple Devices found. The GW is the ethernet gateway. I heard with Docker, updating plugins doesn’t work well so uninstalling the plugin and re-installing would work. As for the Multiple ID’s, try the CG one. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by schmidt660** [comment]
> I made a branch called “test” to fix the Multiple Devices found. The GW is the ethernet gateway. I heard with Docker, updating plugins doesn’t work well so uninstalling the plugin and re-installing would work. As for the Multiple ID’s, try the CG one.
> 
> Sent with [GitHawk](http://githawk.com)

Thanks. Sorry totally new to this - what do I need to amend? I've just tried to uninstall and reinstall the plugin but still no luck. Do I need to amend thew config file at all? Appreciate all your help with this.

**Comment by iRayanKhan** [comment]
>> I made a branch called “test” to fix the Multiple Devices found. The GW is the ethernet gateway. I heard with Docker, updating plugins doesn’t work well so uninstalling the plugin and re-installing would work. As for the Multiple ID’s, try the CG one. ...

@schmidt660 
No worries, Try cd /usr/lib/node_modules
Then do sudo rm -r homebridge-chamberlain
Then reinstall the plugin.
Click this and read issue 5:

https://github.com/caseywebdev/homebridge-chamberlain/wiki/Common-Issues

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by schmidt660** [comment]
> > > I made a branch called “test” to fix the Multiple Devices found. The GW is the ethernet gateway. I heard with Docker, updating plugins doesn’t work well so uninstalling the plugin and re-installing would work. As for the Multiple ID’s, try the CG one. ...
> 
> @schmidt660
> No worries, Try cd /usr/lib/node_modules
> Then do sudo rm -r homebridge-chamberlain
> Then reinstall the plugin.
> Click this and read issue 5:
> 
> https://github.com/caseywebdev/homebridge-chamberlain/wiki/Common-Issues
> 
> Sent with [GitHawk](http://githawk.com)

Thanks. Tried that, reinstalled, but still no luck. Still saying multiple controllable devices. Is there somewhere I can edit where it is picking up the multiple devices from?

**Comment by iRayanKhan** [comment]
@schmidt660 That is expected behavior now all you need to is 
in the config.json file, add the device ID that starts with CG. It should work then.

**Comment by schmidt660** [comment]
Thanks. Where exactly does the ID go? Is it just ‘Device ID: XXXXXXX’ ?

**Comment by iRayanKhan** [comment]
@schmidt660 it goes here:
```json
{
  "accessory": "Chamberlain",
  "name": "Main Garage Door",
  "username": "your mychamberlain.com email",
  "password": "your mychamberlain.com password",
  "deviceId": "xxx"
}
```
If you need help with the config file let me know.

**Comment by schmidt660** [comment]
Working again! Adding the device ID fixed it. Thank you so much

**Comment by iRayanKhan** [comment]
Anytime, glad this worked!
