### ISSUE TITLE
Chamberlain Openers No Longer Responding: HTTP 500 Error

### ISSUE THREAD

**Issue by beaverly72** [iRayanKhan/homebridge-chamberlain#63]
# Explain the issue occuring:
receiving Error: invalid response, got HTTP 500 error

# Expected Result

# Info
iOS Version: 13.1.3
Plugin Version: v1.0.5
HomeBridge Version: 0.4.50
Node/Npm Version: ?

# Log Output:
at /usr/lib/node_modules/homebridge-chamberlain/src/api.js:27:15
at processTicksAndRejections (internal/process/task_queues.js:89:5)
[10/24/2019, 4:08:42 PM] [Garage Door] Error: invalid response, got HTTP 500: {"code":"500.000","message":"An error occurred while processing the request.","description":"Server Error"}
[chamberlain_homebridge_plugin.txt](https://github.com/caseywebdev/homebridge-chamberlain/files/3769521/chamberlain_homebridge_plugin.txt)

Edited by iRayanKhan:
Removed issue junk text.

**Comment by codetheweb** [comment]
I'm getting the same thing, was working fine until recently.

**Comment by iRayanKhan** [comment]
Question for you both, are you all using docker?

**Comment by huanga** [comment]
Using pm2 for my setup, also seeing the same problem.

I just did `npm up -g` and `npm install -g homebridge-chamberlain`, the issue still persist.

**Comment by codetheweb** [comment]
I'm using Docker, and have the latest version of this plugin installed.

**Comment by iRayanKhan** [comment]
@huanga I am also using PM2 and am using the v4Api branch. 

@codetheweb I saw an issue with docker and this plugin with the V5 Update not going well.

Theres 2 fixes you both can try
. # 1 is [to see this comment ](https://github.com/caseywebdev/homebridge-chamberlain/issues/60#issuecomment-546127153)

or # 2 is [to see the Common Issues page](https://github.com/caseywebdev/homebridge-chamberlain/issues/60#issuecomment-546127153)

Step 5 in the common issues page seems to be working for people. 

If that doesn't work, try the V4Api Branch.

**Comment by huanga** [comment]
@iRayanKhan > I'm using 1.0.5 of the package, source code suggests I'm using v4.1 API:


```
$ cat /usr/lib/node_modules/homebridge-chamberlain/src/api.js
...
...
      ApiVersion: '4.1',
...
...
```

**Comment by beaverly72** [comment]
Option #2 fixed it for me. I saw this fix earlier, but the error message made me think it was unrelated.  Thanks!

Should I close this?

**Comment by iRayanKhan** [comment]
@beaverly72 I'll close it thanks! @huanga #64
