### ISSUE TITLE
Not Responding: Error 500

### ISSUE THREAD

**Issue by iRayanKhan** [iRayanKhan/homebridge-chamberlain#64]
This issue seems to be popping up for a lot of people. I still wish to keep them separate from one another since people have different setups, but this issue will be used for general discussion and potential fixes that are suggested to help fix this issue.

**Comment by iRayanKhan** [comment]
Seems like many users who are using docker, show that the API file still says V4.1 which means the plugin didn't update properly.
So delete the plugin file from
```/usr/lib/node_modules``` then re-install the plugin and see if the ```api.js``` file shows the V5 APi.

**Comment by schmidt660** [comment]
> Seems like many users who are using docker, show that the API file still says V4.1 which means the plugin didn't update properly.
> So delete the plugin file from
> `/usr/lib/node_modules` then re-install the plugin and see if the `api.js` file shows the V5 APi.

Just checked api.js in '/volume1/docker/homebridge/node_modules/homebridge-chamberlain/src/api.js' and it still says 'ApiVersion: '4.1'

Is there a new api.js file I can replace this with, that has V5?

**Comment by schmidt660** [comment]
> Seems like many users who are using docker, show that the API file still says V4.1 which means the plugin didn't update properly.
> So delete the plugin file from
> `/usr/lib/node_modules` then re-install the plugin and see if the `api.js` file shows the V5 APi.

I've deleted and reinstalled the plugin a number of times

**Comment by schmidt660** [comment]
Although saying that, it also says 4.1 on the code on GitHub so not sure

**Comment by tekie99** [comment]
I am not running docker... running straight off macOS and it has also not been working for me either.. I have updated to the latest release, and the api.js seems to be identical to the release now but I am plagued with the 500 errors on both of my doors: 

[10/25/2019, 9:16:20 AM] [Detatched Garage Door] Error: invalid response, got HTTP 500: {"code":"500.000","message":"An error occurred while processing the request.","description":"Server Error"}
    at /usr/local/lib/node_modules/homebridge-chamberlain/src/api.js:27:15
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[10/25/2019, 9:16:21 AM] [Main Garage Door] Error: invalid response, got HTTP 500: {"code":"500.000","message":"An error occurred while processing the request.","description":"Server Error"}
    at /usr/local/lib/node_modules/homebridge-chamberlain/src/api.js:27:15
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by iRayanKhan** [comment]
Something isn’t syncing with the update. I’ll push a new release to see if it’ll update the api.js. 
Try the test branch for now since it seems to be working 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by huanga** [comment]
Just checked my side (npm/pm2 install, not Docker), running package 1.0.5, `api.js` shows 4.1 on top, but v5 API later down in the file for the actual requests. The file seems to be the same as the one on github:

[Line 18](https://github.com/caseywebdev/homebridge-chamberlain/blob/master/src/api.js#L18):
`      ApiVersion: '4.1',`

[Line 67](https://github.com/caseywebdev/homebridge-chamberlain/blob/master/src/api.js#L67):
`        pathname: '/api/v5/My',`

[Line 83](https://github.com/caseywebdev/homebridge-chamberlain/blob/master/src/api.js#L83):
`          pathname: '/api/v5/Accounts/' + AccountId + '/Devices',`

[Line 140](https://github.com/caseywebdev/homebridge-chamberlain/blob/master/src/api.js#L140):
`            pathname: '/api/v5/accounts/' + AccountId + '/devices/' + MyQDeviceId,`

[Line 154](https://github.com/caseywebdev/homebridge-chamberlain/blob/master/src/api.js#L154):
`            pathname: '/api/v5.1/Accounts/' + AccountId + '/Devices/' + MyQDeviceId + '/actions',
`

==========

I've added `console.log` locally to each of the API calls, and it looks like the error is coming from `getDeviceAttribute`. Not sure how much more debug I can put in on this until a bit later (jobby job). Hopefully this points us in the right direction?

**Comment by iRayanKhan** [comment]
@huanga This definitely should help, can you try out the V4Api Branch? That's what I'm using and it works for me.

**Comment by iRayanKhan** [comment]
Ok @huanga this fix has worked for everyone so far so let's see if it will for you:
To get new device ID's, try out the following:
```mkdir GarageBridge``` - New Directory

```cd GarageBridge``` - Change Directory path to this folder

``` nano config.json``` - Make a new config.json file with just this plugin in the config and device id's blank.
 
``` cd ``` - Change back to main directory (important) 

Make sure to change the port, Mac address, and name.

```homebridge -U ~/GarageBridge/``` - Runs HomeBridge for that specific path and watch the output show device ID's. 

Enter in the new deviceID's in your ```config.json``` in your main HomeBridge bridge. You can now delete the test bridge using ```sudo rm -r GarageBridge/```.

**Comment by huanga** [comment]
Was restarting homebridge continuously anyway, so I just commented out the device ID, restarted it, nabbed the new IDs (somehow there are two, first one worked though), and restarted it again. Seems to be working now -- no visual confirmation, but the MyQ app seems to suggest it is working, so there's that.

Thanks for this!

**Comment by iRayanKhan** [comment]
Yup, it spits out 2 ID's (will be fixed soon), since one is for the ethernet gateway.

**Comment by tekie99** [comment]
I'm all fixed now! Thanks guys!  It was a brutal week for me without my doors being in Homekit, lol... I almost broke down and bought the $70 Homekit add-on from Chamberlain

**Comment by hodgson-ken** [comment]
> Ok @huanga this fix has worked for everyone so far so let's see if it will for you:
> To get new device ID's, try out the following:
> `mkdir GarageBridge` - New Directory
> 
> `cd GarageBridge` - Change Directory path to this folder
> 
> ` nano config.json` - Make a new config.json file with just this plugin in the config and device id's blank.
> 
> `cd` - Change back to main directory (important)
> 
> Make sure to change the port, Mac address, and name.
> 
> `homebridge -U ~/GarageBridge/` - Runs HomeBridge for that specific path and watch the output show device ID's.
> 
> Enter in the new deviceID's in your `config.json` in your main HomeBridge bridge. You can now delete the test bridge using `sudo rm -r GarageBridge/`.

Where do we start this process (in which folder)?  I want to test this, but am not sure where to be when typing: mkdir GarageBridge, etc.

**Comment by iRayanKhan** [comment]
It’s done in the default directory. Are you using a pi or something else? If a pi, just type 
```
cd
```
Then start the command chain I posted.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by codetheweb** [comment]
Thanks for the help @iRayanKhan, updating the device ID worked.  Had to use the one starting with `CG`.

**Comment by iRayanKhan** [comment]
Anytime @codetheweb, glad it's fixed now.

**Comment by hodgson-ken** [comment]
Just a pi so I’ll try that tomorrow. Thanks. 

UPDATE: All fixed!  Thank you!

Ken Hodgson

**Comment by fisch55** [comment]
> Anytime @codetheweb, glad it's fixed now.

Hi, I've got the same message like the others...

`[10/27/2019, 7:33:43 AM] [Garagentor] Error: invalid response, got HTTP 500: {"code":"500.000","message":"An error occurred while processing the request.","description":"Server Error"}
    at res.text.then.body (/usr/lib/node_modules/homebridge-chamberlain/src/api.js:27:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)`

**Comment by fisch55** [comment]
Ok ...it works with CGxxxxxx THX

**Comment by janthony6** [comment]
I can confirm that the deviceid should start with CG now.

Easier way to accomplish finding your new deviceid is to go into your current config and delete change the word "deviceId" to anything else - in my case I just deleted 1 letter.  then restart homebridge and check your logs.  it will show all the deviceid numbers.  I grabbed the CG one and plugged it in, then fixed "deviceI" to "deviceId" and that solved it.

**Comment by tekie99** [comment]
this afternoon this started cropping up after working for a couple days without issue:

[10/29/2019, 6:52:03 PM] [Main Garage Door] SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at /usr/local/lib/node_modules/homebridge-chamberlain/src/api.js:33:19
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[10/29/2019, 6:52:03 PM] [Detatched Garage Door] SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at /usr/local/lib/node_modules/homebridge-chamberlain/src/api.js:33:19
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by JamesCaudill** [comment]
I also started getting the same error as @tekie99.  It was working for a couple of days, and just noticed this morning that the garage door was unresponsive.  No change in the config file.

**Comment by hodgson-ken** [comment]
Same here. It dropped sometime last night, it seems. 

Ken Hodgson

**Comment by JamesCaudill** [comment]
The error: SyntaxError: Unexpected token < in JSON at position 0 is a duplicate issue.  See [issue #68](https://github.com/caseywebdev/homebridge-chamberlain/issues/68) that has a fix for a user agent change.  Seemed to work for me.

**Comment by iRayanKhan** [comment]
This issue seems to be resolved and issue 68 has also been resolved.
