### ISSUE TITLE
No device found

### ISSUE THREAD

**Issue by FJRGuy** [iRayanKhan/homebridge-chamberlain#7]
Noob here trying to make this HomeBridge thing work. Tried too much too fast and nothing worked. After uninstalling everything and starting from scratch, I have installed HomeBridge and the HomeBridge-Chamberlain plugin. HomeBridge now starts and loads config.json fine, but I get the following error repeatedly until I kill the process. My initial thought was I had my password incorrect, but went as far as resetting it completely to no avail. I'm pretty sure this is going to be a "Doh!" moment when I figure it out but hoping you can shed some light.

[9/30/2016, 5:00:01 PM] [Garage Door] Error: No controllable devices found at getDeviceList.then.devices (/usr/local/lib/node_modules/homebridge-chamberlain/src/api.js:70:31) at process._tickCallback (internal/process/next_tick.js:103:7)

Jeff

**Comment by caseywebdev** [comment]
Try version `1.0.1` (just released) and let me know if that works.
