### ISSUE TITLE
Error: EAI_AGAIN

### ISSUE THREAD

**Issue by hepcat72** [iRayanKhan/homebridge-chamberlain#71]
# Explain the issue occuring:

My garage door stopped responding to commands maybe a month or so ago.  Siri always says "Your garage door is opening" as if the command worked, but the garage door never budges.  I have not waited long enough to see if it times out.  Just looking at the log now.  It's filled with these errors:

```
[10/28/2019, 11:34:33 AM] [Garage Door] { FetchError: request to https://myqexternal.myqdevice.com/api/v4/User/Validate failed, reason: getaddrinfo EAI_AGAIN myqexternal.myqdevice.com myqexternal.myqdevice.com:443
    at ClientRequest.<anonymous> (/usr/lib/node_modules/homebridge-chamberlain/node_modules/node-fetch/index.js:133:11)
    at ClientRequest.emit (events.js:197:13)
    at TLSSocket.socketErrorListener (_http_client.js:397:9)
    at TLSSocket.emit (events.js:197:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)

  name: 'FetchError',
  message:
   'request to https://myqexternal.myqdevice.com/api/v4/User/Validate failed, reason: getaddrinfo EAI_AGAIN myqexternal.myqdevice.com myqexternal.myqdevice.com:443',
  type: 'system',
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN' }
```

# Expected Result

Garage door responds to commands.

# Info
iOS Version: 12.4.1
Plugin Version: Sorry - I don't know how to look this up.
HomeBridge Version: 0.4.49
Node/Npm Version: 6.9.0

# Log Output:

See above.

**Comment by zwoop** [comment]
I'm having a similar issue, my garage doors stopped responding, I upgraded home bridge and all plugins, but now I get

```
[11/6/2019, 7:51:16 AM] [Garage Secondary] Error: invalid response, got HTTP 500: {"code":"500.000","message":"An error occurred while processing the request.","description":"Server Error"}
    at res.text.then.body (/usr/local/lib/node_modules/homebridge-chamberlain/src/api.js:27:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[11/6/2019, 7:51:16 AM] [Garage Main] Error: invalid response, got HTTP 500: {"code":"500.000","message":"An error occurred while processing the request.","description":"Server Error"}
    at res.text.then.body (/usr/local/lib/node_modules/homebridge-chamberlain/src/api.js:27:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

Did Chamberlain change something on their servers? New URL(s) ?

**Comment by hepcat72** [comment]
Mine is a client error (443) and yours is a server error (500). I could be wrong, but I suspect they are unrelated.

**Comment by zwoop** [comment]
I'm thinking that Chamberlain changed the server names (or something), and maybe we get different errors based on versions of software / setup ?

**Comment by hepcat72** [comment]
We are both getting responses from the servers, so there are servers with those names that exist.  If I go to https://myqexternal.myqdevice.com, I get a response:

```
{
    "SecurityToken": "",
    "ReturnCode": "0",
    "ErrorMessage": "please contact customer care, supportID: 18229368976910989492",
    "CorrelationId": ""
}
```

But that's not a proper POST.  It does show that the server exists though.  I suspect that in my case, it's likely that the [Chamberlain API has changed](https://www.reddit.com/r/homeassistant/comments/djw9bm/myq_garage_door_unavailable_api_changes/).  My homebridge is making a validation request and the server is responding that the client (homebridge) made a mistake.

I still suspect these are different issues.  Yours is saying that the server encountered a fatal error.  The protocol however should be the same whether we have different versions of the plugin or not: POST some json as a request, get a json response - so it shouldn't result in different categories of errors.  Whether the request json is invalid shouldn't in principle cause a fatal server error, though I can't be absolutely sure.  I recommend you submit an issue with your error (if you haven't already).

**Comment by hepcat72** [comment]
It looks like Chamberlain no longer supports the web interface.  When I go here: https://www.mychamberlain.com/Login.aspx

I see:

> Moving to Mobile
> In order to provide the best myQ experience, this web login will no longer be supported. Download the new app and use your current login. For more information check out our FAQ.

**Comment by iRayanKhan** [comment]
In regards to the error 500, check #64. For error 443 I think it's an expired security token and the fix for #64 should also work for it. I'll have more of a look into it once I get home.

**Comment by iRayanKhan** [comment]
> It looks like Chamberlain no longer supports the web interface. When I go here: https://www.mychamberlain.com/Login.aspx
> 
> I see:
> 
> > Moving to Mobile
> > In order to provide the best myQ experience, this web login will no longer be supported. Download the new app and use your current login. For more information check out our FAQ.

I can still login to that and use the web interface, it shows when my garages were last closed, but I haven't tried to see if I can open it since I'm not home atm.

**Comment by hepcat72** [comment]
You're right.  I was able to login to the web interface as well.  Look's like it's not officially dead yet.

Anyway, I tried the solution from #64, but I do not get a new device ID output on the console.  Instead, I get this error spit out over and over every few seconds:

```
[11/6/2019, 2:38:41 PM] [Garage Door] Error: No controllable devices found
    at getDeviceList.then.devices (/usr/lib/node_modules/homebridge-chamberlain/src/api.js:71:31)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
```

I can still control my garage door with the MyQ app, so I'm not sure what to make of the error.

Incidentally, I had to enter the homebridge-hdmi-cec stuff in the temporary config or else homebridge gets a bunch of type errors and shuts down immediately.

I suppose it's possible I messed something up in the recommended resolution steps in #64?  Here's what I did:

```
mkdir GarageBridge
cd GarageBridge/
nano config.json
cd
homebridge -U ~/GarageBridge/
```

I copied and edited the config.json content from my original (changing the bridge name, username, port, & pin):

```
{
    "bridge": {
        "name": "HomebridgeDebug",
        "username": "CC:22:3D:E3:CE:01",
        "port": 51827,
        "pin": "031-45-155"
    },

    "description": "Homebridge config file for describing devices Siri will control.",

    "accessories": [
        {
            "accessory": "Chamberlain",
            "name": "Garage Door",
            "username": "__MY_EMAIL__",
            "password": "__MY_PASSWORD__"
        }
    ],
    "platforms": [
        {
            "platform": "CEC",
            "manufacturer": "Magnavox",
            "model": "32ME303V/F7 A",
            "sources": [
                {
                    "name": "Raspberry Pi",
                    "address": "1.0.0.0"
                },
                {
                    "name": "Mac Mini",
                    "address": "2.0.0.0"
                }
            ]
        }
    ]
}
```

**Comment by hepcat72** [comment]
I can see the garage door connected to my network via Airport Utility, but I don't see it in bonjour browser or in avahi-browse.  I assume it's supposed to be discoverable via bonjour?  Since it's not there, is there a way to make a DHCP reservation and set it up via IP?

**Comment by hepcat72** [comment]
OK.  I updated npm, then updated homebridge-chamberlain, re-ran the procedure from #64, got 2 possible/different device IDs, updated my config.json, restarted homebridge, and tested it out and it worked.

Also - after the update, I had restarted homebridge before the config update and got the same 500 server error @zwoop was seeing.
