### ISSUE TITLE
invalid response, got HTTP 500

### ISSUE THREAD

**Issue by mc-hamster** [iRayanKhan/homebridge-chamberlain#73]
# Explain the issue occurring:
Opening / Closing garage door through home app on either ios or mac os does not work. 500 errors are in the log file.

I was previously running 1.0.2 but since upgraded to 1.0.7.

Followed the instructions in:

https://github.com/caseywebdev/homebridge-chamberlain/wiki/Common-Issues

Noticed that my deviceId has changed from a purely numerical ID to one starting with CG. I updated the config.json and still get the server error.

This has been happening for about a week.

ps - Good work on the plugin!

# Expected Result
Garage door opens / closes.

# Info
iOS Version: ios13.2 & macos 10.14.6
Plugin Version: homebridge-chamberlain@1.0.7
HomeBridge Version: homebridge@0.4.50
Node/Npm Version: 3.5.2

# Log Output:

Nov  7 22:22:03 Shanghai homebridge[31221]: [11/7/2019, 10:22:03 PM] [Garage Door] Error: invalid response, got HTTP 500: {"code":"500.000","message":"An error occurred while processing the request.","description":"Server Error"}
Nov  7 22:22:03 Shanghai homebridge[31221]:     at res.text.then.body (/usr/local/lib/node_modules/homebridge-chamberlain/src/api.js:27:15)
Nov  7 22:22:03 Shanghai homebridge[31221]:     at <anonymous>
Nov  7 22:22:03 Shanghai homebridge[31221]:     at process._tickCallback (internal/process/next_tick.js:188:7)
Nov  7 22:22:13 Shanghai homebridge[31221]: [11/7/2019, 10:22:13 PM] [Garage Door] Error: invalid response, got HTTP 500: {"code":"500.000","message":"An error occurred while processing the request.","description":"Server Error"}
Nov  7 22:22:13 Shanghai homebridge[31221]:     at res.text.then.body (/usr/local/lib/node_modules/homebridge-chamberlain/src/api.js:27:15)
Nov  7 22:22:13 Shanghai homebridge[31221]:     at <anonymous>
Nov  7 22:22:13 Shanghai homebridge[31221]:     at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by mc-hamster** [comment]
While I was on 1.0.2, I had a different error message. See below:

Nov  7 21:52:36 Shanghai homebridge[971]: [11/7/2019, 9:52:36 PM] [Garage Door] { FetchError: request to https://myqexternal.myqdevice.com/api/v4/User/Validate failed, reason: connect ETIMEDOUT 40.112.59.58:443
Nov  7 21:52:36 Shanghai homebridge[971]:     at ClientRequest.<anonymous> (/usr/local/lib/node_modules/homebridge-chamberlain/node_modules/node-fetch/index.js:133:11)
Nov  7 21:52:36 Shanghai homebridge[971]:     at emitOne (events.js:116:13)
Nov  7 21:52:36 Shanghai homebridge[971]:     at ClientRequest.emit (events.js:211:7)
Nov  7 21:52:36 Shanghai homebridge[971]:     at TLSSocket.socketErrorListener (_http_client.js:387:9)
Nov  7 21:52:36 Shanghai homebridge[971]:     at emitOne (events.js:116:13)
Nov  7 21:52:36 Shanghai homebridge[971]:     at TLSSocket.emit (events.js:211:7)
Nov  7 21:52:36 Shanghai homebridge[971]:     at emitErrorNT (internal/streams/destroy.js:64:8)
Nov  7 21:52:36 Shanghai homebridge[971]:     at _combinedTickCallback (internal/process/next_tick.js:138:11)
Nov  7 21:52:36 Shanghai homebridge[971]:     at process._tickCallback (internal/process/next_tick.js:180:9)
Nov  7 21:52:36 Shanghai homebridge[971]:   name: 'FetchError',
Nov  7 21:52:36 Shanghai homebridge[971]:   message: 'request to https://myqexternal.myqdevice.com/api/v4/User/Validate failed, reason: connect ETIMEDOUT 40.112.59.58:443',
Nov  7 21:52:36 Shanghai homebridge[971]:   type: 'system',
Nov  7 21:52:36 Shanghai homebridge[971]:   errno: 'ETIMEDOUT',
Nov  7 21:52:36 Shanghai homebridge[971]:   code: 'ETIMEDOUT' }

**Comment by iRayanKhan** [comment]
Did you try Step 5 in the common issues page?

**Comment by mc-hamster** [comment]
Yes, my purely numerical ID to one starting with CG. I updated the config.json and still get the server error.

Also restarted homebridge after updating config.json.

**Comment by iRayanKhan** [comment]
Try cleaning out your persist and cache files if tiu can and uninstall, and reinstall the plugin. Also are you using docker?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mc-hamster** [comment]
That did it!

I deleted the persist and cache files, deleted homebridge from my home, restarted homebridge, re-added the bridge and now everything works again.

There was no need to uninstall/reinstall the plugin.

This is running on Ubuntu 18.04.3 LTS in a VM on ESXi.

**Comment by iRayanKhan** [comment]
Glad it's working now; going to close this issue.
