### ISSUE TITLE
Account Lockout

### ISSUE THREAD

**Issue by jfirwin** [iRayanKhan/homebridge-chamberlain#74]
# Explain the issue occuring:
I am using `homebridge-config-ui-x v4.6.3` to install this plugin. When I set it up and entered my account details it returned the logs stating that I was locked out, it continues to try to successfully access the api, but fails to do so. I uninstalled this plugin, reset my password, logged in on my phone to check that I was no longer locked out, and then tried once more to install, configure and restart homebridge. Upon reset It locks the account and forces a password reset again.

# Expected Result
Successful access to the api, without locking out. I'm just hoping I'm not the only one dealing with this issue and it's something fixable and not myq locking down their api.

# Info
iOS Version: 13.2.2
Plugin Version: v1.0.8 (via homebridge-config-ui-x v4.6.3)
HomeBridge Version: 0.4.50
Node/Npm Version: v12.12.0 / v6.11.3

# Log Output:
The log continually sends this message:
```[11/12/2019, 11:47:30 AM] [Garage Door] Error: invalid response, got HTTP 401: {"code":"401.207","message":"Unauthorized","description":"The user is locked out."}
    at /usr/local/lib/node_modules/homebridge-chamberlain/src/api.js:27:15
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[11/12/2019, 11:47:41 AM] [Garage Door] Error: invalid response, got HTTP 401: {"code":"401.207","message":"Unauthorized","description":"The user is locked out."}
    at /usr/local/lib/node_modules/homebridge-chamberlain/src/api.js:27:15
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[11/12/2019, 11:47:52 AM] [Garage Door] Error: invalid response, got HTTP 401: {"code":"401.207","message":"Unauthorized","description":"The user is locked out."}
    at /usr/local/lib/node_modules/homebridge-chamberlain/src/api.js:27:15
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[11/12/2019, 11:48:02 AM] [Garage Door] Error: invalid response, got HTTP 401: {"code":"401.207","message":"Unauthorized","description":"The user is locked out."}
    at /usr/local/lib/node_modules/homebridge-chamberlain/src/api.js:27:15
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

```

**Comment by iRayanKhan** [comment]
Few Questions:
1) Can you use the normal app?
2) This may be a user agent change, but it works for me fine.

**Comment by jfirwin** [comment]
I'm not sure exactly what happened. I'm setting up homebridge for the first time and just getting things started. I was having issues with the `MyQ2` plugin as well and after some resets and patience I got that plugin to work. When it failed it wasn't locking me out of my MyQ account and forcing password resets. I just wanted to bring attention to it in case it's related to the `homebridge-chamberlain` plugin. I didn't try doing a manual install though so idk.

**Comment by iRayanKhan** [comment]
It may be best doing a manual install. I've never seen this issue before and either the API didn't update your accounts info (which it should), or it's the plugin install. MyQ2 and this plugin rely on the same api.

**Comment by jfirwin** [comment]
I'll test it out tonight, thanks!

**Comment by iRayanKhan** [comment]
Hey @jfirwin, did you have time to test it out? If so, did it work?

**Comment by jfirwin** [comment]
Yeah I reinstalled Homebridge and Homebridge config and was able to get the plugin working correctly. I don't know what the issue was but it doesn't seem like it was related to this plugin.
