### ISSUE TITLE
Error: No controllable devices found

### ISSUE THREAD

**Issue by epijimenez** [iRayanKhan/homebridge-chamberlain#77]
# Explain the issue occuring:
Error: No controllable devices found
at getDeviceList.then.devices (/usr/local/lib/node_modules/homebridge-chamberlain/src/api.js:99:36)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)

# Expected Result
Find the home lock connected through the MyQ app

# Info
iOS Version: iOS 13
Plugin Version: homebridge-chamberlain@1.0.8
HomeBridge Version: 0.4.50
Node/Npm Version: 6.4.1

# Log Output:
[2019-11-23 03:06:42] [Garage Door] Error: No controllable devices found
    at getDeviceList.then.devices (/usr/local/lib/node_modules/homebridge-chamberlain/src/api.js:99:36)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)

**Comment by epijimenez** [comment]
PS. maybe this is a unexpected change, but I had lockitron (home lock) which the company was bought by MyQ/chamberlain and got thrown into the same group of devices.

**Comment by iRayanKhan** [comment]
Hi @epijimenez. Currently this plugin is for garages only. If someone would like to make a PR and add lock support I would merge it in. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by iRayanKhan** [comment]
@epijimenez I feel like taking a crack at this, I need some info about the locks that may be private, so if you would like to email me @ rayankhan04 [@] iCloud.com I can get some more info and see what I can get going with this.

**Comment by iRayanKhan** [comment]
Hi @epijimenez I didn't hear back, if you'd like this implemented please email me at the given email, I need more info before I can dig into this. 

Closing for now.

**Comment by epijimenez** [comment]
Sorry Ryan. I’ve moved to another lock solution and I tried to set up a new account so you can do as you please without any privacy issues, but a family member gave away the lock already. 

Thanks for trying. 👍

>>

**Comment by pponce** [comment]
@iRayanKhan i have two Lockitron bolts and would love to be able to expose them to HomeKit via MyQ. What information would you need?

**Comment by iRayanKhan** [comment]
Hi @pponce,
Does the plugin return deviceID’s for your locks?

**Comment by pponce** [comment]
I’ll have a look. At some point i switched to using homebridge/myq2 I think when all the api changes occurred.
I’ll switch back to chamberlain and see. I can also run some api queries and let you know what it returns.

**Comment by pponce** [comment]
when i run 
http://api.myqdevice.com/api/v5.1/Accounts/{{AccountID}}/Devices
I get a count of 3 devices returned. My two hubs and my single garage door.
I don't see my two locks in the returned list of devices.
I do see two "physical devices" associated with each of my hubs though.
but my guess is that one of those physical devices is for any attached garage doors and the other is for the built in light perhaps.

I'm using Postman to execute the api calls.
