### ISSUE TITLE
Remote Lighting Control Support

### ISSUE THREAD

**Issue by ahnyerkeester** [iRayanKhan/homebridge-chamberlain#78]
My MyQ garage door opener came with two remote lighting controllers which I use in my living room. The garage door opener is the hub for them. Is there a way to add them to Homebridge along with the garage door opener? I used to have access via a different Homebridge plug in but I believe the API changed and it never got updated.

**Comment by iRayanKhan** [comment]
Hi @ahnyerkeester there is an open issue to support locks currently, I’ll see if I can add these lights too. Can you please find the plugin that was able to this, as it would help tremendously.  Thanks, Rayan.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ahnyerkeester** [comment]
Awesome, Thanks Rayan.

**Comment by iRayanKhan** [comment]
Anytime, @ahnyerkeester.

So this got some attention on Reddit, I would like some info to start being able to do this.

I need multiple people, or someone with two or more light controllers, to email me the device ID's to see if I can spot a consistent pattern, to distinguish the light V garage.

my email is rayankhan04 [@] iCloud .com

**Comment by ahnyerkeester** [comment]
Sending mine along.

**Comment by ahnyerkeester** [comment]
Okay, I know I located them before but I can't recall how. Googling answers doesn't really help either. What's the easiest way to get my device IDs?

**Comment by iRayanKhan** [comment]
Hi @ahnyerkeester look at how to generate device ID's here: (This shouldn't effect current install)
[Check Step 5 here](https://github.com/caseywebdev/homebridge-chamberlain/wiki/Common-Issues)

**Comment by ahnyerkeester** [comment]
Thank you @iRayanKhan , the IDs are on their way!

In case anyone else wants to do this and is using HOOBS, here's how to make it work:

When it says "Make a new config.json file with just this plugin in the config and device id's blank." what you need to do is copy the `Server`, `Client`, and `Bridge` portion of `~/.hoobs/etc/config.json` and paste that into the new json. Then add this section:

`"accessories": [{`
         `"accessory": "Chamberlain",`
            `"plugin_map": {`
                `"plugin_name": "chamberlain",`
                `"index": 0`
            `},`
            `"name": "Garage Door",`
            `"username": "YourUsername",`
            `"password": "YourPassword"`
       `}]`

Alternatively, you could `cp ~/.hoobs/etc/config.json ~/GarageBridge/` then delete all the other devices, the line `"deviceId": "xxxxxxxxxx"` and the comma from the end of the line before it from the Chamberlain device.

Either way, after you get the new json built, copy and paste its contents into jsonlint.com and validate it. Fix errors as needed.

To run it, cd to `~/.hoobs/node_modules/@hoobs/homebridge/bin` and in there you can use the command pretty much as it is in Step 5 in the link. I had to add `./` before `homebridge` to get it to work.

**Comment by iRayanKhan** [comment]
Hi, I have some progress on light controller support. 
This update (may) break current installations as you have to add a new parameter to your config. 
I will have something concrete published tomorrow, follow the Light_Controller branch. I don't have any light controllers to test, so please be advised that I rely heavily on testers.

**Comment by ahnyerkeester** [comment]
Standing by to test!

**Comment by iRayanKhan** [comment]
Sweet, in the mean time do you know how to make a new Homebridge instance, and also it's recommended to make a new HomeKit home for this too

**Comment by ahnyerkeester** [comment]
I don't know how to do that. I was just planning on testing it in my current setup. I figured I can always fall back to the latest version of the plug in.

**Comment by iRayanKhan** [comment]
Yeah you always could, just wanted to make sure nothing gets messed up in the process. 
You are running off a Pi correct?

**Comment by ahnyerkeester** [comment]
I am now on a Mac Mini because the RPI couldn't handle Time Machine backups. But I still have the RPI set up and can use it as a test bed.

**Comment by iRayanKhan** [comment]
Hey @ahnyerkeester I have pushed some changed to the light_controller branch. 
There is a new parameter to the config.json file so be advised to add that. Here is an example of it:
```json
{
  "accessory": "Chamberlain",
  "name": "Light",
  "username": "your mychamberlain.com email",
  "password": "your mychamberlain.com password",
  "deviceId": "xxx",
  "isLight": true
}
```

Please let me know if it works, thanks!

Edit:
I didn't have to specify the ```isLight``` parameter for my existing garage doors, so you only need to add that snippet of the config for a new light accessory and not tinker with the normal garage doors.

Edit 2:

I have also added obstruction detection, it is based off the light controller branch, so if you would like to test both features, it is possible now.

**Comment by ahnyerkeester** [comment]
I'm having a hard time downloading that specific branch. Still working on it.

**Comment by iRayanKhan** [comment]
Hi @ahnyerkeester try this:
```npm install — save homebridge-chamberlain@beta.```
additionally, if you wish to test obstruction detection, change the @ to alpha. 


Edit: Alpha and Beta is now published.

Alpha - Light_Controller & Obstruction_Detection
Beta   - Light_Controller (Only)

**Comment by iRayanKhan** [comment]
Hey @ahnyerkeester, did it work for you? If so I'm ready to merge

**Comment by ahnyerkeester** [comment]
I'm not sure that it installed correctly. When I added a light, it showed up as a garage door and didn't control the light. Then again, I'm running it on HOOBS. I'm going to try to set up another RPI with Homebridge and try it again, but I'm going out of town this week so I won't be able to do it right away.

**Comment by iRayanKhan** [comment]
I think HOOBS may be the issue too. 
I wrote in the plugin form to HOOBS yesterday, to prepare for a plugin breaking update and to locate the new config in the branches. So I guess either they updated it and are waiting for V2.0 to come out, or didn't update it yet. 

Also clear cachedAccessories when you update.

**Comment by ahnyerkeester** [comment]
Sorry that took so long. I did a clean install of Homebridge on a clean install of Raspbian and tried it. The switch shows up but it doesn't seem to do anything. Tried different device IDs. No change.

**Comment by iRayanKhan** [comment]
Is there anything from the debug?

**Comment by ahnyerkeester** [comment]
From the log. After I push the button, this error happens and the service restates.

`[2/15/2020, 18:14:42] TypeError: this.api.setDeviceAttribute is not a function
    at module.exports.setTargetLightState (/usr/lib/node_modules/homebridge-chamberlain/src/chamberlain-accessory.js:136:21)`
`    at Characteristic.On.emit (events.js:223:5)`
`    at Characteristic.On.Characteristic.setValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:321:10)`
`    at Bridge.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:882:22)`
`    at Array.forEach (<anonymous>)`
`    at Bridge.Accessory._handleSetCharacteristics (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:822:8)`
`    at HAPServer.emit (events.js:223:5)`
`    at HAPServer._handleCharacteristics (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:974:10)`
`    at HAPServer.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)`
`    at IncomingMessage.emit (events.js:223:5)`
`    at endReadableNT (_stream_readable.js:1185:12)`
`    at processTicksAndRejections (internal/process/task_queues.js:81:21)`

**Comment by iRayanKhan** [comment]
Let me do some more digging, hope to get this fixed this week.

**Comment by iRayanKhan** [comment]
So does the Switch actually show up in HomeKit, or is it showing up as a light?

**Comment by ahnyerkeester** [comment]
It shows up in HomeKit as a switch. Every time I press it, it generates the same error as above and restarts Homebridge. Doesn't change the light.

**Comment by iRayanKhan** [comment]
Sorry for delayed response, I think I forgot to commit some changes that added the set function. I will do another beta soon. Eta 1 or 2 days.

**Comment by iRayanKhan** [comment]
I made a [new](https://github.com/iRayanKhan/homebridge-chamberlain/tree/new_Light_Controller) branch here. It should work now (I hope). Let me know if you need this published to NPM. Also I recommend not using HOOBS with this beta due to version conflicts.

**Comment by ahnyerkeester** [comment]
So is this the beta one? It shows up as a garage door and I get this error when it runs:

`Error: invalid response, got HTTP 500: {"code":"500.000","message":"An error occurred while processing the request.","description":"Server Error"}`
    `at /usr/lib/node_modules/homebridge-chamberlain/src/api.js:27:15`
    `at processTicksAndRejections (internal/process/task_queues.js:97:5)`

**Comment by ahnyerkeester** [comment]
Same error as above. Still no affect on the light.

**Comment by iRayanKhan** [comment]
Oops, had it commented out xD
I just fixed it, try git cloning it again please.

**Comment by johnsills1** [comment]
Please post it to npm and let us know the name you use

**Comment by ahnyerkeester** [comment]
Now I'm getting a very odd failure when I try to install it:
`pi@raspberrypi:~ $ sudo npm install -save homebridge-chamberlain@beta`
`npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EAI_AGAIN: request to https://registry.npmjs.org/homebridge-chamberlain failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org`
`npm WARN registry Using stale data from https://registry.npmjs.org/ due to a request error during revalidation.`
`^C[..................] - loadDep:underscore: sill removeObsoleteDep removing hom`
`pi@raspberrypi:~ $ sudo npm install -save homebridge-chamberlain@beta`
`npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EAI_AGAIN: request to https://registry.npmjs.org/homebridge-chamberlain failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org`
`npm WARN registry Using stale data from https://registry.npmjs.org/ due to a request error during revalidation.`
`npm WARN saveError ENOENT: no such file or directory, open '/home/pi/package.json'`
`npm WARN enoent ENOENT: no such file or directory, open '/home/pi/package.json'`
`npm WARN pi No description`
`npm WARN pi No repository field.`
`npm WARN pi No README data`
`npm WARN pi No license field.`

`+ homebridge-chamberlain@1.0.9`
`updated 1 package in 20.882s`

**Comment by iRayanKhan** [comment]
Yeah this release isn't tagged ```@beta```, I have to use a new tag every time. I will publish a new beta and list the new naming convention once it's published.

**Comment by ahnyerkeester** [comment]
That makes a lot of sense. I'll be watching.

**Comment by iRayanKhan** [comment]
Just Published, use the tag ```@rc1``` and see if that works.

**Comment by ahnyerkeester** [comment]
Still didn't work:

`pi@raspberrypi:~ $ sudo npm install -save homebridge-chamberlain@rc1`
`npm ERR! code ETARGET`
`npm ERR! notarget No matching version found for homebridge-chamberlain@rc1.`
`npm ERR! notarget In most cases you or one of your dependencies are requesting`
`npm ERR! notarget a package version that doesn't exist.`

`npm ERR! A complete log of this run can be found in:`
`npm ERR!     /root/.npm/_logs/2020-03-16T22_46_18_071Z-debug.log`

**Comment by iRayanKhan** [comment]
do ```sudo npm I -g homebridge-chamberlain@rc1```

**Comment by ahnyerkeester** [comment]
Did `sudo npm install -g homebridge-chamberlain@rc1` and got the same result. Doing `sudo npm I` was an invalid option.

**Comment by iRayanKhan** [comment]
I think since the repo transferred I have to update the package.json. Give me a few minutes

**Comment by iRayanKhan** [comment]
try ```@rc2```

**Comment by ahnyerkeester** [comment]
Installs perfectly. Now it generates this error:

```
[3/17/2020, 05:51:38] Loaded config.json with 1 accessories and 1 platforms.
[3/17/2020, 05:51:38] ---
[3/17/2020, 05:51:38] ====================
[3/17/2020, 05:51:38] ERROR LOADING PLUGIN homebridge-chamberlain:

[3/17/2020, 05:51:38] /usr/lib/node_modules/homebridge-chamberlain/src/api.js:179
  setDeviceAttribute(options = {}) {

                                   ^

SyntaxError: Unexpected token '{'
    at wrapSafe (internal/modules/cjs/loader.js:1072:16)
    at Module._compile (internal/modules/cjs/loader.js:1122:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-chamberlain/src/chamberlain-accessory.js:2:13)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
[3/17/2020, 05:51:38] ====================

**Comment by ahnyerkeester** [comment]
Sorry, I clicked the wrong button and closed the issue!

**Comment by iRayanKhan** [comment]
Had me excited, thought I fixed it xD.
I think forgot to lint my code, simple fix.
I'll do it in the morning and ship rc 3. Thanks for the testing and sorry for the delay.

**Comment by iRayanKhan** [comment]
Try ```@rc3``` please.

Edit: I had to install suing: sudo npm i -g homebridge-chamberlain@1.3.1

maybe that will work. The plugin runs fine for me. Also I may need to change one last thing if this thing doesn't work.

**Comment by ahnyerkeester** [comment]
The `@1.3.1` worked.
Shows up as a switch but when I click it, I get this error and then Homebridge restarts:
```
[3/19/2020, 14:35:39] TypeError: this.getSecurityTokenAndMyQDeviceId is not a function
    at /usr/lib/node_modules/homebridge-chamberlain/src/api.js:182:12
    at module.exports.maybeRetry (/usr/lib/node_modules/homebridge-chamberlain/src/api.js:111:12)
    at module.exports.setDeviceAttribute (/usr/lib/node_modules/homebridge-chamberlain/src/api.js:181:17)
    at module.exports.setTargetLightState (/usr/lib/node_modules/homebridge-chamberlain/src/chamberlain-accessory.js:137:21)
    at Characteristic.On.emit (events.js:311:20)
    at Characteristic.On.Characteristic.setValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:321:10)
    at Bridge.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:882:22)
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._handleSetCharacteristics (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:822:8)
    at HAPServer.emit (events.js:311:20)

**Comment by iRayanKhan** [comment]
Just published rc4 with the missing functions.
If the switch works, but nothing happens the light url changed and there may be come things I can try to see if it's just a number off.

**Comment by ahnyerkeester** [comment]
I'm not able to get rc4. Is that the name you used?

**Comment by ahnyerkeester** [comment]
Figured it out. `1.3.2` :)

Now I get this:
```
[3/19/2020, 22:23:02] [Light?] SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at /usr/lib/node_modules/homebridge-chamberlain/src/api.js:33:19
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[3/19/2020, 22:23:03] [Light?] SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at /usr/lib/node_modules/homebridge-chamberlain/src/api.js:33:19
    at processTicksAndRejections (internal/process/task_queues.js:97:5) @

**Comment by iRayanKhan** [comment]
Finally getting somewhere. So yes the api did change the url. I need some personal info if you don't mind. My email is ```rayankhan04 @ iCloud.com```. It will speed up the process significantly.

**Comment by ahnyerkeester** [comment]
Just emailed you.

**Comment by iRayanKhan** [comment]
@ahnyerkeester did the new RC work by chance?

**Comment by ahnyerkeester** [comment]
@iRayanKhan, is there a newer one than 1.3.2? That's the last one I tested.

**Comment by iRayanKhan** [comment]
Yes, it is @1.4.5

**Comment by ahnyerkeester** [comment]
Didn't work and here's the error:
```
[3/24/2020, 18:22:13] TypeError: this.getSecurityTokenAndMyQDeviceId is not a function
    at /usr/lib/node_modules/homebridge-chamberlain/src/api.js:171:12
    at module.exports.maybeRetry (/usr/lib/node_modules/homebridge-chamberlain/src/api.js:111:12)
    at module.exports.setDeviceAttribute (/usr/lib/node_modules/homebridge-chamberlain/src/api.js:170:17)
    at module.exports.setTargetLightState (/usr/lib/node_modules/homebridge-chamberlain/src/chamberlain-accessory.js:137:21)
    at Characteristic.On.emit (events.js:311:20)
    at Characteristic.On.Characteristic.setValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:321:10)
    at Bridge.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:882:22)
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._handleSetCharacteristics (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:822:8)
    at HAPServer.emit (events.js:311:20)

**Comment by ahnyerkeester** [comment]
Just popped in to make sure I didn't miss anything. How are things going? You okay with the pandemic and all?

**Comment by iRayanKhan** [comment]
Hi sorry to ghost, Im doing well thanks, schools busy and all. Are you doing good as well?

So I can't debug this issue, and neither can my JS buddy. I am escalating this issue to a veteran dev as I don't get why this isn't working. I am so sorry for the delay.

**Comment by ahnyerkeester** [comment]
No problems, this is a voluntary project, it just hit me that I hadn't heard from you for a while and hoped the virus hadn't gotten to you. Even with the stay-at-home I know we're busy. We're doing fine but I sure miss eating out!

**Comment by iRayanKhan** [comment]
Lol yeah thanks for checking up, I hope you are doing well too. I am low key lost with light controller support, so I am going to inquire some senior or retired home bridge devs regarding this one.

**Comment by iRayanKhan** [comment]
Hwy @ahnyerkeester it might be worth getting in contact with he dev of [this](https://github.com/hjdhjd/homebridge-myq) plugin, as he seems to be working on light controllers.
