### ISSUE TITLE
HTTP 500

### ISSUE THREAD

**Issue by timgris** [iRayanKhan/homebridge-chamberlain#80]
# Explain the issue occuring:
This is my first plugin for homebridge. I am getting an error 500:
Error: invalid response, got HTTP 500: {"code":"500.000","message":"An error occurred while processing the request.","description":"Server Error"}
    at /usr/lib/node_modules/homebridge-chamberlain/src/api.js:27:15
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

# Expected Result
Able to see/open/close garage

# Info
iOS Version: 13.3
Plugin Version: 1.0.8
HomeBridge Version: 0.4.50
Node/Npm Version: 12.14.0/6.13.4

# Log Output:

**Comment by timgris** [comment]
I am pretty sure this is PEBCAK.  I do have multiple devices and am used to a single-digit device ID from my openhab time.  However, when I remove the deviceID to find the device IDs, I see a longer string.  Switching to that it appears to have removed the error.  On to the next step.

**Comment by Ghazgkull** [comment]
I just got this same error on my install which had been working for months with no changes. I suspect there may have been a breaking change to the service?

**Comment by Ghazgkull** [comment]
Sure enough. It looks like the deviceId from Chamberlain changed. To fix the problem, I renamed the "deviceId" property in the config.json to some dummy key (e.g. "deviceIdOld"), restarted homebridge (systemctl restart homebridge) and then looked in the logs to get the updated device Id.
