### ISSUE TITLE
Homebridge can't connect to garage door -- invalid response, got HTTP 500

### ISSUE THREAD

**Issue by sebastienb** [iRayanKhan/homebridge-chamberlain#83]
# Explain the issue occuring:
No response in Home app  and on homebridge console i'm getting this error over and over.
```
[1/22/2020, 7:05:36 PM] [Garage Door] Error: invalid response, got HTTP 500: {"code":"500.000","message":"An error occurred while processing the request.","description":"Server Error"}
    at /homebridge/node_modules/homebridge-chamberlain/src/api.js:27:15
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
```
# Expected Result
(Give a description of the expected behaviour.)

# Info
iOS Version:
Plugin Version: homebridge-chamberlain v1.0.8
HomeBridge Version: 0.4.50
Node/Npm Version: v12.14.1

# Log Output:
(If applicable)

**Comment by iRayanKhan** [comment]
Are you on the latest version of the plugin? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sebastienb** [comment]
yes I'm on v1.0.8

**Comment by sebastienb** [comment]
Got it to work, my device ID changed. It was working for a while now and recently stoped working. 

## How i solved it
- removed device id
- restarted homebridge
- got new ID

Thanks
