### ISSUE TITLE
Chamberlin Secure Video

### ISSUE THREAD

**Issue by inforatio** [iRayanKhan/homebridge-chamberlain#87]
The newest Chamberlin openers provide for support "Secure Video" in addition to remote opening/closing using MyQ. Can you update your plug-in to support this new feature so that users don't have to go back and forth between apps? And all functionality can be accesses through Apple Home?

https://www.chamberlain.com/garage-door-openers/secure-view-camera-opener

**Comment by iRayanKhan** [comment]
Wow, I had no idea they made this.
Did this come with your home or did you buy it?

Also, I don't know if I can integrate this with my plugin. Do you get any deviceID's for this camera by chance?

**Comment by inforatio** [comment]
I’m having it installed in a couple of weeks. I can look into your questions, though.

D

**Comment by iRayanKhan** [comment]
Thanks for the info, I don't know if the api will produce keys which is why I was asking.

Even if it did give the keys, I'd have to reformat a lot of this plugin and add ffmpeg support. 
I also wonder if the camera depending on their definition of "secure", if the camera can only be accessed from their own app.

**Comment by iRayanKhan** [comment]
If the "api" we are using for this plugin doesn't get camera feed, I wonder if there's a way to get an RTSP stream from it, then hope homebridge-camera-ffmpeg adds HKSV soon.

**Comment by inforatio** [comment]
I’m actually surprised Chamberlin provides an api. I tried talking with tech support, but they are clueless. They just told me that Chamberlin only works with partner apps.

At the current time, I’m not aware of any integrations with Nest, or anything like that that are using the camera feed. But, that might change. And, if it does. They would have to provide a device ID.

Best,
David

**Comment by iRayanKhan** [comment]
Yeah it's not really an official API that this plugin uses. Camera feed may be difficult as we'd need an RTSP url.

**Comment by iRayanKhan** [comment]
Hi @inforatio were you able to get these installed yet by chance?

**Comment by inforatio** [comment]
No, everything is on hold, as I can’t even get my installer to come by now. At any rate, I was thinking, could you also use the widely held FFmpeg Homebridge plug-in with this solution?

**Comment by iRayanKhan** [comment]
I was going to say that, but if these openers don't have an RTSP stream, there's nothing we can do. If does have RTSP, then that ffmpeg plugin was meant for this.

**Comment by iRayanKhan** [comment]
After doing some more research no camera feed gets it's own deviceID, and even if it did we would need an rtsp url to access the stream. And if you do obtain an RTSP url from the likes of Wireshark or guessing, the camera-ffmpeg plugin is the way to go.
