### ISSUE TITLE
Anyway to have another for node v4.2.6?

### ISSUE THREAD

**Issue by KradKrad** [iRayanKhan/homebridge-chamberlain#9]
I would like to use your homebridge plugin, but I heavily rely on the homebridge-wink plugin for a bulk of my devices.  I attempted to upgrade my nodejs and got everything to work but homebridge-wink because it can't work with node6.

Any chance you can make another branch for node v4.2.6?

much appreciated if you can.

**Comment by caseywebdev** [comment]
What error does homebridge-wink fail with? The better long term solution is for them to get up to date with the latest node rather than downgrade other libs.

**Comment by KradKrad** [comment]
agreed... but that plugin has to interface with hundreds of devices and supposedly has been in the works with a 6.6 node update.  It won't work with 5.x or 6.x.  I have tried mulitple times.  Is it hard to have a seperate package for your plugin? do you have to re-write it?

**Comment by caseywebdev** [comment]
It would be a rewrite dropping all of the newer JS syntax. Feel free to fork it and change whatever you'd like, I'm not going to do that though.

**Comment by caseywebdev** [comment]
Also check out https://github.com/nfarina/homebridge-liftmaster which might work for you.

**Comment by KradKrad** [comment]
/usr/local/lib/node_modules/homebridge/node_modules/mdns/lib/dns_sd.js:35
throw ex;
^

Error: Module version mismatch. Expected 46, got 48.
at Error (native)
at Object.Module._extensions..node (module.js:434:18)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object. (/usr/local/lib/node_modules/homebridge/node_modules/mdns/lib/dns_sd.js:24:20)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)

**Comment by caseywebdev** [comment]
Try removing `homebridge` and reinstalling it.
