### ISSUE TITLE
MyQ Garage Camera

### ISSUE THREAD

**Issue by wamota** [iRayanKhan/homebridge-chamberlain#91]
My MyQ garage door opener came with a built-in camera that connects to the garage door hub. Is there a way to add the camera to Homebridge together with the garage door opener so I can monitor the garage door on the camera when it opens and closes?

The MyQ Bridge adds the camera to Homekit but they charge a monthly fee to have it detect and report motion. Is there a way to add it to HomeBridge too?

BTW thanks for all your work on this plugin, it works perfectly.

**Comment by iRayanKhan** [comment]
Hi there, there was an existing issue #87 about this.
To integrate the camera to HomeBridge/HomeKit you would need the RTSP url. If you get that, the homebridge-camera-ffmpeg plugin would do the trick. Would paying once to add the camera then stop paying work?

I'm glad the plugin works for you,
have a good day and stay safe.

**Comment by wamota** [comment]
Thanks for the guidance... I'm struggling to find the RTSP url of the camera, I guess Chamberlain doesn't want to make it easy to bypass their $70 "gateway". Any idea how to find the url? running nmap or Wireshark on my wifi seems a bit much just to find an url but I'm thinking on trying to get it that way.

**Comment by iRayanKhan** [comment]
It appears to be the only way to get it, unless iSpyDataBase has it listed. So if I'm understanding correctly you need the $70 Gateway and pay an additional fee?

**Comment by iRayanKhan** [comment]
Closing as this can't be integrated with this plugin and has other potential workarounds.
