### ISSUE TITLE
Siri Name of Door Recognition

### ISSUE THREAD

**Issue by gamertyke** [iRayanKhan/homebridge-chamberlain#92]
Hard to get Siri to recognize the name of the door for some reason. I have a MyQ hub/sensor on one garage door, and an Insigina native Homekit device on the other. The Insignia is pretty unreliable connecting to HomeKit, often going "No response" which is why I bought the MyQ device. 

When the Insignia does work, I can say something like "Open garage right door" and it works, however this language does not working for the MyQ/Home bridge setup. The naming is the same (Left Door/Right door), both in the Garage "room" in the home app. The MyQ connection to Homebridge/HomeKit/Home app is rock solid, so awesome job on the plugin! Just wondering if there's a way to get Siri to recognize the device in a more natural way.

**Comment by iRayanKhan** [comment]
So personally I name my doors

"Single Garage" and "Double Garage". 

Siri and this plugin aren't tied, as that is a HomeKit issue and is a common bug. 

I hope these names or suggestions help, but yeah sorry this plugin or any plugin really integrate with Siri as it is a HomeKit issue.
