### ISSUE TITLE
Debug Level Logging

### ISSUE THREAD

**Issue by TheEngineerGuy** [iRayanKhan/homebridge-chamberlain#95]
Hi Guys,
I was wondering if there is a way for me to enable Debug level logging from our plugin here. When I run Homebridge -D, I can see debug logs for all other plugins, but this one.

Looking for your thoughts and help.

**Comment by iRayanKhan** [comment]
Currently the plugin kinda does self debug as any API errors or fails and api calls are all logged to console. So the -D flag essentially isn’t necessary

**Comment by TheEngineerGuy** [comment]
OK, I was more looking at understanding when notifications are sent out etc, because I don't those messages in logs today.

**Comment by iRayanKhan** [comment]
I don't think home bridge can tell when notifications are sent out due to a HomeKit limitation and that notifications are server side not plugin side. For this reason I can't really do anything about it unless HomeKit ADK gets updated to support this.

**Comment by TheEngineerGuy** [comment]
HI @iRayanKhan , yes and no my friend. Notification related communication works in two ways. 1 which requires Apple HomeKit server intervention, 2 which does not require Apple HomeKit server. I can explain it as below:

```
Case #1, when you are away from home and connected to a non-home-network

Plugin -----------------------------> HomeBridge --------------------------------------------------------------> HomeHub -------------------> Apple HomeKit Server --------------> Apple Device
(Sends accessory state               (Generates an Event on Accessory state update,                              (Forwards the Event          (Sends event to                      (Uses the event, and based on notification settings 
 update to HomeBridge)                and sends it to all local devices registered with HomeBridge directly,      to Apple HomeKit Server)     all Away-from-home devices)          decides to where to show the notification or not)
                                      & designated home hub devices under _homekit._tcp)

Case #2, when you are at home and connected to your home wifi network.


Plugin -----------------------------> HomeBridge -------------------------------------------------------------->  Apple Device
(Sends accessory state               (Generates an Event on Accessory state update,                              (Uses the event, and based on notification settings
update to HomeBridge)                 and sends it to all local devices registered with HomeBridge directly,      decides to where to show the notification or not)
                                      & designated home hub devices under _homekit._tcp)
```

So, in both cases HomeBridge is the one generating the initial event of state change. So, it must maintain logs of which devices it sent the TCP unicast communication to for state change event.

I hope this helps.

**Comment by iRayanKhan** [comment]
@TheEngineerGuy Hello,

By chance do you know any current plugin that contains this functionality? I would love to see an example, and will add it after the V2.0.3 update.

**Comment by TheEngineerGuy** [comment]
I think from plugin Point of view, you can only Log when plugin called homebridge with a state change/update (MyQ2 does this). To actually log 'notification send out' might be a Homebridge feature, because HB manages notifications while plugin manages state change call outs. So, as long as from plugin end you are able to log state changes/updates, you should be fine.

**Comment by iRayanKhan** [comment]
Closing: This plugin is now being deprecated. Please use [this](https://github.com/hjdhjd/homebridge-myq) plugin.
