### ISSUE TITLE
Additional Door states

### ISSUE THREAD

**Issue by TheEngineerGuy** [iRayanKhan/homebridge-chamberlain#96]
Hi guys,
Currently this plugin only seems to provide Open, closed, opening and closing states. However, I saw an instance today where garage door got stuck after opening about 90%, so MyQ app showed door as stuck open, but our plugin still deemed it as closed to the homekit.

So, could we look at adding some more door states to our plugin?

**Comment by iRayanKhan** [comment]
Currently there is an obstruction detection branch, it’s not fully implemented yet, but is being worked on.

**Comment by TheEngineerGuy** [comment]
Got it. In the mean time, if the door is partially open can we just mark it as open?

**Comment by iRayanKhan** [comment]
Hi there,
Do you mind trying the newStates branch? Not sure if I integrated the states in properly, but worth a shot.

**Comment by TheEngineerGuy** [comment]
How do I target installation of new states branch? Is it under Beta?

**Comment by iRayanKhan** [comment]
Look into git clone, after swapping the files, go into the new homebridge-chamberlain folder and run (sudo) npm install.


I can't publish these to NPM currently as I'm not home and don't have node in this environment.

**Comment by TheEngineerGuy** [comment]
All good @iRayanKhan We can wait a bit.

**Comment by iRayanKhan** [comment]
So PR #100 tested new states, and it didn't work. It may be changes with the new api V5 or 5.1, but I gotta do more digging.

**Comment by iRayanKhan** [comment]
Hey @TheEngineerGuy,

Open, Closed, Opening, Closing work on my end. The "Obstruction Detected" is something I am trying to get done. Can you confirm that the 4 states work for you?

**Comment by TheEngineerGuy** [comment]
4 states are working now. Thanks for implementing!

**Comment by iRayanKhan** [comment]
Closing: This plugin is now being deprecated. Please use [this](https://github.com/hjdhjd/homebridge-myq) plugin.
