### ISSUE TITLE
Duplicate Device IDs for Two Garage Doors

### ISSUE THREAD

**Issue by Aidan711** [iRayanKhan/homebridge-chamberlain#97]
# Explain the issue occuring:

I had both garage doors working for a very long time until they suddenly stopped working. After updating the Chamberlain plugin, each garage door give the same two device IDs (CG0846025217, CG0846025218). I tried to troubleshoot by switching around the device IDs, but that didn't work. I removed Garage Door 2 from my MyQ account and Garage Door 1 worked fine. 

HomeBridge Error Messages:

[2020-5-13 20:52:33] [Garage Door 1] Error: Multiple controllable devices found: CG0846025217, CG0846025218
    at getDeviceList.then.devices (/usr/lib/node_modules/homebridge-chamberlain/src/api.js:106:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[2020-5-13 20:52:33] [Garage Door 2] Error: Multiple controllable devices found: CG0846025217, CG0846025218
    at getDeviceList.then.devices (/usr/lib/node_modules/homebridge-chamberlain/src/api.js:106:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

Config:

    "accessories": [
      {
          "accessory": "Chamberlain",
          "name": "Garage Door 1",
          "username": "email",
          "password": "password",
          "deviceID": "CG0846025217"
      },
      {
          "accessory": "Chamberlain",
          "name": "Garage Door 2",
          "username": "email",
          "password": "password",
          "deviceID": "CG0846025218"
      }
    ],

**Comment by conrad-vanl** [comment]
Just tried setting up for the first time, and I'm seeing the same. Two garage doors:

```
Error: Multiple controllable devices found: CG08602AFF64, GW0F0016BCF1, CG08602AFEF9, GW0F0016BCCD
2020-05-14T05:07:21.713325597Z app[web.1]:     at /homebridge/node_modules/homebridge-chamberlain/src/api.js:106:13
```

**Comment by iRayanKhan** [comment]
Try updating the plugin or uninstalling and reinstalling. Device ID"s with GW are not supported in this plugin as they are not garage doors the CG device ID is the one you are after. Also it's interesting to see your deviceID's be spaced by 1 digit.

**Comment by Aidan711** [comment]
The plugin is fully updated. I can try uninstalling and reinstalling tonight and let you know what happens.

**Comment by Aidan711** [comment]
I did a clean install of the plugin and it is still giving out the same error message.

**Comment by conrad-vanl** [comment]
I configured the plugin using the `CG` IDs and added the doors to the Home app. They show up as "not responding" in the app and any time I try to toggle one in the app, I get error printouts in homebridge log, like:

```
[5/15/2020, 12:59:43 PM] [Garage Door 1] Error: Multiple controllable devices found: CG08602AFF64, GW0F0016BCF1, CG08602AFEF9, GW0F0016BCCD
     at /homebridge/node_modules/homebridge-chamberlain/src/api.js:106:13
     at runMicrotasks (<anonymous>)
     at processTicksAndRejections (internal/process/task_queues.js:97:5)
[5/15/2020, 12:59:43 PM] [Garage Door 2] Error: Multiple controllable devices found: CG08602AFF64, GW0F0016BCF1, CG08602AFEF9, GW0F0016BCCD
     at /homebridge/node_modules/homebridge-chamberlain/src/api.js:106:13
     at runMicrotasks (<anonymous>)
     at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

Happy to do more debugging if you can point me in the right direction!

```
"accessories": [{
      "accessory": "Chamberlain",
      "name": "Garage Door 1",
      "username": "...",
      "password": "...",
      "deviceID": "CG08602AFF64"
    },
    {
      "accessory": "Chamberlain",
      "name": "Garage Door 2",
      "username": "...",
      "password": "...",
      "deviceID": "CG08602AFEF9"
    }
  ]
```

**Comment by Aidan711** [comment]
Finally solved it! Here's a couple of things I did to fix the issue:
1. Update Homebridge plugin
2. Update Node.js to the latest version (mine was at 8.11 and the current version is 10.20)
3. Uninstall Chamberlain plugin and restart whatever device you're using for Homebridge
4. Reinstall and run with no device IDs
5. Assign the device IDs back into the config and test

If it still does not work, I took a few extra steps.
- Install config-ui-x if you haven't already
- Set up the plugin and open the localhost in browser
- Install the Chamberlain plugin from the plugins tab by using the search bar
- Follow the in-browser setup instructions
- Run Homebridge and see if that works

**Comment by conrad-vanl** [comment]
Interesting. I run homebridge on a docker container. I can rebuild the container fresh and the error persists, which means at least for me it's not a restart or npm install issue. Appears to use node 12.16.x so don't think it's that either.

I do not use `config-ui-x`.
 
```
"homebridge": "^1.0.4",
"homebridge-chamberlain": "^1.6.0",
```

@Aidan711 does this plugin still spit out the the `GW` ids?

**Comment by Aidan711** [comment]
Oddly enough, I never had any GW IDs when using the plugin. I am using the Chamberlain Group myQ Smart Garage Door Opener Chamberlain MYQ-G0301 system, which might make a difference.

**Comment by iRayanKhan** [comment]
Can both of y'all send a picture of your openers and model types please?

**Comment by conrad-vanl** [comment]
I have two Liftmaster 8550W. Do you need a photo of something specific or just used to identify?

**Comment by iRayanKhan** [comment]
I just need a picture to identify it, maybe the button configuration on the device (blur info like S/N) may help. Also how does it look in the app?

**Comment by iRayanKhan** [comment]
Is there any more updates regarding this issue? If not, I will close it.
