### ISSUE TITLE
Change type of device so HomeKit automations work without popup notification needing okay

### ISSUE THREAD

**Issue by eoren1** [iRayanKhan/homebridge-chamberlain#98]
Currently, HomeKit requires user input for any automations involving garage door openers. So if I set an automation to open the garage door when I arrive home, I get a popup from my iPhone that I have to click on before the door opens.

If the MyQ device were disguised as a switch, I don't think this would occur and HomeKit would act without user intervention.

**Comment by iRayanKhan** [comment]
Hi there,

I could implement this, but it will take time. 

In the mean time you could use homebridge-dummy to create an automation to control the garage and have the automation toggle the switch.

Like if switch is on open garage and have your automation turn the switch on. 


Thanks for using the plugin.

**Comment by eoren1** [comment]
Thanks Rayan

Actually the dummy switch idea worked perfectly! Maybe you can add that in the plugin to help other newbies sidestep the HomeKit prompts.

Eyal

**Comment by iRayanKhan** [comment]
It can be in the road map to add the dummy switch to the plugin itself, but since a plugin for it exists I won't be adding it natively yet. 

In the future if this picks up more traction I will add it natively into the plugin via config.


Thank you for the suggestion!
